export const Emojis = {
    "grinning face": "😀",
    "grinning face with big eyes": "😃",
    "grinning face with smiling eyes": "😄",
    "beaming face with smiling eyes": "😁",
    "grinning squinting face": "😆",
    "grinning face with sweat": "😅",
    "rolling on the floor laughing": "🤣",
    "face with tears of joy": "😂",
    "slightly smiling face": "🙂",
    "upside-down face": "🙃",
    "winking face": "😉",
    "smiling face with smiling eyes": "😊",
    "smiling face with halo": "😇",
    "smiling face with hearts": "🥰",
    "smiling face with heart-eyes": "😍",
    "star-struck": "🤩",
    "face blowing a kiss": "😘",
    "kissing face": "😗",
    "smiling face": "☺️",
    "kissing face with closed eyes": "😚",
    "kissing face with smiling eyes": "😙",
    "smiling face with tear": "🥲",
    "face savoring food": "😋",
    "face with tongue": "😛",
    "winking face with tongue": "😜",
    "zany face": "🤪",
    "squinting face with tongue": "😝",
    "money-mouth face": "🤑",
    "hugging face": "🤗",
    "face with hand over mouth": "🤭",
    "shushing face": "🤫",
    "thinking face": "🤔",
    "zipper-mouth face": "🤐",
    "face with raised eyebrow": "🤨",
    "neutral face": "😐",
    "expressionless face": "😑",
    "face without mouth": "😶",
    "smirking face": "😏",
    "unamused face": "😒",
    "face with rolling eyes": "🙄",
    "grimacing face": "😬",
    "lying face": "🤥",
    "relieved face": "😌",
    "pensive face": "😔",
    "sleepy face": "😪",
    "drooling face": "🤤",
    "sleeping face": "😴",
    "face with medical mask": "😷",
    "face with thermometer": "🤒",
    "face with head-bandage": "🤕",
    "nauseated face": "🤢",
    "face vomiting": "🤮",
    "sneezing face": "🤧",
    "hot face": "🥵",
    "cold face": "🥶",
    "woozy face": "🥴",
    "dizzy face": "😵",
    "exploding head": "🤯",
    "cowboy hat face": "🤠",
    "partying face": "🥳",
    "disguised face": "🥸",
    "smiling face with sunglasses": "😎",
    "nerd face": "🤓",
    "face with monocle": "🧐",
    "confused face": "😕",
    "worried face": "😟",
    "slightly frowning face": "🙁",
    "frowning face": "☹️",
    "face with open mouth": "😮",
    "hushed face": "😯",
    "astonished face": "😲",
    "flushed face": "😳",
    "pleading face": "🥺",
    "frowning face with open mouth": "😦",
    "anguished face": "😧",
    "fearful face": "😨",
    "anxious face with sweat": "😰",
    "sad but relieved face": "😥",
    "crying face": "😢",
    "loudly crying face": "😭",
    "face screaming in fear": "😱",
    "confounded face": "😖",
    "persevering face": "😣",
    "disappointed face": "😞",
    "downcast face with sweat": "😓",
    "weary face": "😩",
    "tired face": "😫",
    "yawning face": "🥱",
    "face with steam from nose": "😤",
    "pouting face": "😡",
    "angry face": "😠",
    "face with symbols on mouth": "🤬",
    "smiling face with horns": "😈",
    "angry face with horns": "👿",
    "skull": "💀",
    "skull and crossbones": "☠️",
    "pile of poo": "💩",
    "clown face": "🤡",
    "ogre": "👹",
    "goblin": "👺",
    "ghost": "👻",
    "alien": "👽",
    "alien monster": "👾",
    "robot": "🤖",
    "grinning cat": "😺",
    "grinning cat with smiling eyes": "😸",
    "cat with tears of joy": "😹",
    "smiling cat with heart-eyes": "😻",
    "cat with wry smile": "😼",
    "kissing cat": "😽",
    "weary cat": "🙀",
    "crying cat": "😿",
    "pouting cat": "😾",
    "see-no-evil monkey": "🙈",
    "hear-no-evil monkey": "🙉",
    "speak-no-evil monkey": "🙊",
    "kiss mark": "💋",
    "love letter": "💌",
    "heart with arrow": "💘",
    "heart with ribbon": "💝",
    "sparkling heart": "💖",
    "growing heart": "💗",
    "beating heart": "💓",
    "revolving hearts": "💞",
    "two hearts": "💕",
    "heart decoration": "💟",
    "heart exclamation": "❣️",
    "broken heart": "💔",
    "red heart": "❤️",
    "orange heart": "🧡",
    "yellow heart": "💛",
    "green heart": "💚",
    "blue heart": "💙",
    "purple heart": "💜",
    "brown heart": "🤎",
    "black heart": "🖤",
    "white heart": "🤍",
    "hundred points": "💯",
    "anger symbol": "💢",
    "collision": "💥",
    "dizzy": "💫",
    "sweat droplets": "💦",
    "dashing away": "💨",
    "hole": "🕳️",
    "bomb": "💣",
    "speech balloon": "💬",
    "eye in speech bubble": "👁️‍🗨️",
    "left speech bubble": "🗨️",
    "right anger bubble": "🗯️",
    "thought balloon": "💭",
    "zzz": "💤",
    "waving hand": "👋",
    "raised back of hand": "🤚",
    "hand with fingers splayed": "🖐️",
    "hand with fingers splayed: light skin tone": "🖐🏻",
    "hand with fingers splayed: medium-light skin tone": "🖐🏼",
    "hand with fingers splayed: medium skin tone": "🖐🏽",
    "hand with fingers splayed: medium-dark skin tone": "🖐🏾",
    "hand with fingers splayed: dark skin tone": "🖐🏿",
    "raised hand": "✋",
    "vulcan salute": "🖖",
    "OK hand": "👌",
    "pinched fingers": "🤌",
    "pinching hand": "🤏",
    "victory hand": "✌️",
    "victory hand: light skin tone": "✌🏻",
    "victory hand: medium-light skin tone": "✌🏼",
    "victory hand: medium skin tone": "✌🏽",
    "victory hand: medium-dark skin tone": "✌🏾",
    "victory hand: dark skin tone": "✌🏿",
    "crossed fingers": "🤞",
    "love-you gesture": "🤟",
    "sign of the horns": "🤘",
    "call me hand": "🤙",
    "backhand index pointing left": "👈",
    "backhand index pointing right": "👉",
    "backhand index pointing up": "👆",
    "middle finger": "🖕",
    "backhand index pointing down": "👇",
    "index pointing up": "☝️",
    "index pointing up: light skin tone": "☝🏻",
    "index pointing up: medium-light skin tone": "☝🏼",
    "index pointing up: medium skin tone": "☝🏽",
    "index pointing up: medium-dark skin tone": "☝🏾",
    "index pointing up: dark skin tone": "☝🏿",
    "thumbs up": "👍",
    "thumbs down": "👎",
    "raised fist": "✊",
    "oncoming fist": "👊",
    "left-facing fist": "🤛",
    "right-facing fist": "🤜",
    "clapping hands": "👏",
    "raising hands": "🙌",
    "open hands": "👐",
    "palms up together": "🤲",
    "handshake": "🤝",
    "folded hands": "🙏",
    "writing hand": "✍️",
    "writing hand: light skin tone": "✍🏻",
    "writing hand: medium-light skin tone": "✍🏼",
    "writing hand: medium skin tone": "✍🏽",
    "writing hand: medium-dark skin tone": "✍🏾",
    "writing hand: dark skin tone": "✍🏿",
    "nail polish": "💅",
    "selfie": "🤳",
    "flexed biceps": "💪",
    "mechanical arm": "🦾",
    "mechanical leg": "🦿",
    "leg": "🦵",
    "foot": "🦶",
    "ear": "👂",
    "ear with hearing aid": "🦻",
    "nose": "👃",
    "brain": "🧠",
    "anatomical heart": "🫀",
    "lungs": "🫁",
    "tooth": "🦷",
    "bone": "🦴",
    "eyes": "👀",
    "eye": "👁️",
    "tongue": "👅",
    "mouth": "👄",
    "baby": "👶",
    "child": "🧒",
    "boy": "👦",
    "girl": "👧",
    "person": "🧑",
    "person: blond hair": "👱",
    "man": "👨",
    "man: beard": "🧔",
    "man: red hair": "👨‍🦰",
    "woman": "👩",
    "person: red hair": "🧑‍🦰",
    "woman: curly hair": "👩‍🦱",
    "person: curly hair": "🧑‍🦱",
    "woman: white hair": "👩‍🦳",
    "person: white hair": "🧑‍🦳",
    "woman: bald": "👩‍🦲",
    "person: bald": "🧑‍🦲",
    "woman: blond hair": "👱‍♀️",
    "older person": "🧓",
    "old man": "👴",
    "old woman": "👵",
    "person frowning": "🙍",
    "person pouting": "🙎",
    "person gesturing NO": "🙅",
    "person gesturing OK": "🙆",
    "person tipping hand": "💁",
    "person raising hand": "🙋",
    "deaf person": "🧏",
    "person bowing": "🙇",
    "person facepalming": "🤦",
    "person shrugging": "🤷",
    "health worker": "🧑‍⚕️",
    "man health worker": "👨‍⚕️",
    "woman health worker": "👩‍⚕️",
    "student": "🧑‍🎓",
    "man student": "👨‍🎓",
    "woman student": "👩‍🎓",
    "teacher": "🧑‍🏫",
    "man teacher": "👨‍🏫",
    "woman teacher": "👩‍🏫",
    "judge": "🧑‍⚖️",
    "man judge": "👨‍⚖️",
    "woman judge": "👩‍⚖️",
    "farmer": "🧑‍🌾",
    "man farmer": "👨‍🌾",
    "woman farmer": "👩‍🌾",
    "cook": "🧑‍🍳",
    "man cook": "👨‍🍳",
    "woman cook": "👩‍🍳",
    "mechanic": "🧑‍🔧",
    "man mechanic": "👨‍🔧",
    "woman mechanic": "👩‍🔧",
    "factory worker": "🧑‍🏭",
    "man factory worker": "👨‍🏭",
    "woman factory worker": "👩‍🏭",
    "office worker": "🧑‍💼",
    "man office worker": "👨‍💼",
    "woman office worker": "👩‍💼",
    "scientist": "🧑‍🔬",
    "man scientist": "👨‍🔬",
    "woman scientist": "👩‍🔬",
    "technologist": "🧑‍💻",
    "man technologist": "👨‍💻",
    "woman technologist": "👩‍💻",
    "singer": "🧑‍🎤",
    "man singer": "👨‍🎤",
    "woman singer": "👩‍🎤",
    "artist": "🧑‍🎨",
    "man artist": "👨‍🎨",
    "woman artist": "👩‍🎨",
    "pilot": "🧑‍✈️",
    "man pilot": "👨‍✈️",
    "woman pilot": "👩‍✈️",
    "astronaut": "🧑‍🚀",
    "man astronaut": "👨‍🚀",
    "woman astronaut": "👩‍🚀",
    "firefighter": "🧑‍🚒",
    "man firefighter": "👨‍🚒",
    "woman firefighter": "👩‍🚒",
    "police officer": "👮",
    "detective": "🕵️",
    "detective: light skin tone": "🕵🏻",
    "detective: medium-light skin tone": "🕵🏼",
    "detective: medium skin tone": "🕵🏽",
    "detective: medium-dark skin tone": "🕵🏾",
    "detective: dark skin tone": "🕵🏿",
    "man detective": "🕵️‍♂️",
    "man detective: light skin tone": "🕵🏻‍♂️",
    "man detective: medium-light skin tone": "🕵🏼‍♂️",
    "man detective: medium skin tone": "🕵🏽‍♂️",
    "man detective: medium-dark skin tone": "🕵🏾‍♂️",
    "man detective: dark skin tone": "🕵🏿‍♂️",
    "woman detective": "🕵️‍♀️",
    "woman detective: light skin tone": "🕵🏻‍♀️",
    "woman detective: medium-light skin tone": "🕵🏼‍♀️",
    "woman detective: medium skin tone": "🕵🏽‍♀️",
    "woman detective: medium-dark skin tone": "🕵🏾‍♀️",
    "woman detective: dark skin tone": "🕵🏿‍♀️",
    "guard": "💂",
    "ninja": "🥷",
    "construction worker": "👷",
    "prince": "🤴",
    "princess": "👸",
    "person wearing turban": "👳",
    "person with skullcap": "👲",
    "woman with headscarf": "🧕",
    "person in tuxedo": "🤵",
    "person with veil": "👰",
    "pregnant woman": "🤰",
    "breast-feeding": "🤱",
    "woman feeding baby": "👩‍🍼",
    "man feeding baby": "👨‍🍼",
    "person feeding baby": "🧑‍🍼",
    "baby angel": "👼",
    "Santa Claus": "🎅",
    "Mrs. Claus": "🤶",
    "mx claus": "🧑‍🎄",
    "superhero": "🦸",
    "supervillain": "🦹",
    "mage": "🧙",
    "fairy": "🧚",
    "vampire": "🧛",
    "merperson": "🧜",
    "elf": "🧝",
    "genie": "🧞",
    "zombie": "🧟",
    "person getting massage": "💆",
    "person getting haircut": "💇",
    "person walking": "🚶",
    "person standing": "🧍",
    "person kneeling": "🧎",
    "person with white cane": "🧑‍🦯",
    "man with white cane": "👨‍🦯",
    "woman with white cane": "👩‍🦯",
    "person in motorized wheelchair": "🧑‍🦼",
    "man in motorized wheelchair": "👨‍🦼",
    "woman in motorized wheelchair": "👩‍🦼",
    "person in manual wheelchair": "🧑‍🦽",
    "man in manual wheelchair": "👨‍🦽",
    "woman in manual wheelchair": "👩‍🦽",
    "person running": "🏃",
    "woman dancing": "💃",
    "man dancing": "🕺",
    "person in suit levitating": "🕴️",
    "person in suit levitating: light skin tone": "🕴🏻",
    "person in suit levitating: medium-light skin tone": "🕴🏼",
    "person in suit levitating: medium skin tone": "🕴🏽",
    "person in suit levitating: medium-dark skin tone": "🕴🏾",
    "person in suit levitating: dark skin tone": "🕴🏿",
    "people with bunny ears": "👯",
    "person in steamy room": "🧖",
    "person climbing": "🧗",
    "person fencing": "🤺",
    "horse racing": "🏇",
    "skier": "⛷️",
    "snowboarder": "🏂",
    "person golfing": "🏌️",
    "person golfing: light skin tone": "🏌🏻",
    "person golfing: medium-light skin tone": "🏌🏼",
    "person golfing: medium skin tone": "🏌🏽",
    "person golfing: medium-dark skin tone": "🏌🏾",
    "person golfing: dark skin tone": "🏌🏿",
    "man golfing": "🏌️‍♂️",
    "man golfing: light skin tone": "🏌🏻‍♂️",
    "man golfing: medium-light skin tone": "🏌🏼‍♂️",
    "man golfing: medium skin tone": "🏌🏽‍♂️",
    "man golfing: medium-dark skin tone": "🏌🏾‍♂️",
    "man golfing: dark skin tone": "🏌🏿‍♂️",
    "woman golfing": "🏌️‍♀️",
    "woman golfing: light skin tone": "🏌🏻‍♀️",
    "woman golfing: medium-light skin tone": "🏌🏼‍♀️",
    "woman golfing: medium skin tone": "🏌🏽‍♀️",
    "woman golfing: medium-dark skin tone": "🏌🏾‍♀️",
    "woman golfing: dark skin tone": "🏌🏿‍♀️",
    "person surfing": "🏄",
    "person rowing boat": "🚣",
    "person swimming": "🏊",
    "person bouncing ball": "⛹️",
    "person bouncing ball: light skin tone": "⛹🏻",
    "person bouncing ball: medium-light skin tone": "⛹🏼",
    "person bouncing ball: medium skin tone": "⛹🏽",
    "person bouncing ball: medium-dark skin tone": "⛹🏾",
    "person bouncing ball: dark skin tone": "⛹🏿",
    "man bouncing ball": "⛹️‍♂️",
    "man bouncing ball: light skin tone": "⛹🏻‍♂️",
    "man bouncing ball: medium-light skin tone": "⛹🏼‍♂️",
    "man bouncing ball: medium skin tone": "⛹🏽‍♂️",
    "man bouncing ball: medium-dark skin tone": "⛹🏾‍♂️",
    "man bouncing ball: dark skin tone": "⛹🏿‍♂️",
    "woman bouncing ball": "⛹️‍♀️",
    "woman bouncing ball: light skin tone": "⛹🏻‍♀️",
    "woman bouncing ball: medium-light skin tone": "⛹🏼‍♀️",
    "woman bouncing ball: medium skin tone": "⛹🏽‍♀️",
    "woman bouncing ball: medium-dark skin tone": "⛹🏾‍♀️",
    "woman bouncing ball: dark skin tone": "⛹🏿‍♀️",
    "person lifting weights": "🏋️",
    "person lifting weights: light skin tone": "🏋🏻",
    "person lifting weights: medium-light skin tone": "🏋🏼",
    "person lifting weights: medium skin tone": "🏋🏽",
    "person lifting weights: medium-dark skin tone": "🏋🏾",
    "person lifting weights: dark skin tone": "🏋🏿",
    "man lifting weights": "🏋️‍♂️",
    "man lifting weights: light skin tone": "🏋🏻‍♂️",
    "man lifting weights: medium-light skin tone": "🏋🏼‍♂️",
    "man lifting weights: medium skin tone": "🏋🏽‍♂️",
    "man lifting weights: medium-dark skin tone": "🏋🏾‍♂️",
    "man lifting weights: dark skin tone": "🏋🏿‍♂️",
    "woman lifting weights": "🏋️‍♀️",
    "woman lifting weights: light skin tone": "🏋🏻‍♀️",
    "woman lifting weights: medium-light skin tone": "🏋🏼‍♀️",
    "woman lifting weights: medium skin tone": "🏋🏽‍♀️",
    "woman lifting weights: medium-dark skin tone": "🏋🏾‍♀️",
    "woman lifting weights: dark skin tone": "🏋🏿‍♀️",
    "person biking": "🚴",
    "person mountain biking": "🚵",
    "person cartwheeling": "🤸",
    "people wrestling": "🤼",
    "person playing water polo": "🤽",
    "person playing handball": "🤾",
    "person juggling": "🤹",
    "person in lotus position": "🧘",
    "person taking bath": "🛀",
    "person in bed": "🛌",
    "people holding hands": "🧑‍🤝‍🧑",
    "women holding hands": "👭",
    "women holding hands: light skin tone, medium-light skin tone": "👩🏻‍🤝‍👩🏼",
    "women holding hands: medium-light skin tone": "👭🏼",
    "women holding hands: medium-light skin tone, medium skin tone": "👩🏼‍🤝‍👩🏽",
    "women holding hands: medium skin tone": "👭🏽",
    "women holding hands: medium skin tone, medium-dark skin tone": "👩🏽‍🤝‍👩🏾",
    "women holding hands: medium-dark skin tone": "👭🏾",
    "women holding hands: medium-dark skin tone, dark skin tone": "👩🏾‍🤝‍👩🏿",
    "women holding hands: dark skin tone": "👭🏿",
    "woman and man holding hands": "👫",
    "woman and man holding hands: light skin tone, medium-light skin tone": "👩🏻‍🤝‍👨🏼",
    "woman and man holding hands: medium-light skin tone": "👫🏼",
    "woman and man holding hands: medium-light skin tone, medium skin tone": "👩🏼‍🤝‍👨🏽",
    "woman and man holding hands: medium skin tone": "👫🏽",
    "woman and man holding hands: medium skin tone, medium-dark skin tone": "👩🏽‍🤝‍👨🏾",
    "woman and man holding hands: medium-dark skin tone": "👫🏾",
    "woman and man holding hands: medium-dark skin tone, dark skin tone": "👩🏾‍🤝‍👨🏿",
    "woman and man holding hands: dark skin tone": "👫🏿",
    "men holding hands": "👬",
    "men holding hands: light skin tone, medium-light skin tone": "👨🏻‍🤝‍👨🏼",
    "men holding hands: medium-light skin tone": "👬🏼",
    "men holding hands: medium-light skin tone, medium skin tone": "👨🏼‍🤝‍👨🏽",
    "men holding hands: medium skin tone": "👬🏽",
    "men holding hands: medium skin tone, medium-dark skin tone": "👨🏽‍🤝‍👨🏾",
    "men holding hands: medium-dark skin tone": "👬🏾",
    "men holding hands: medium-dark skin tone, dark skin tone": "👨🏾‍🤝‍👨🏿",
    "men holding hands: dark skin tone": "👬🏿",
    "kiss": "💏",
    "kiss: woman, man": "👩‍❤️‍💋‍👨",
    "kiss: man, man": "👨‍❤️‍💋‍👨",
    "kiss: woman, woman": "👩‍❤️‍💋‍👩",
    "couple with heart": "💑",
    "couple with heart: woman, man": "👩‍❤️‍👨",
    "couple with heart: man, man": "👨‍❤️‍👨",
    "couple with heart: woman, woman": "👩‍❤️‍👩",
    "family": "👪",
    "family: man, woman, boy": "👨‍👩‍👦",
    "family: woman, woman, boy": "👩‍👩‍👦",
    "family: man, boy": "👨‍👦",
    "family: woman, boy": "👩‍👦",
    "speaking head": "🗣️",
    "bust in silhouette": "👤",
    "busts in silhouette": "👥",
    "people hugging": "🫂",
    "footprints": "👣",
    "monkey face": "🐵",
    "monkey": "🐒",
    "gorilla": "🦍",
    "orangutan": "🦧",
    "dog face": "🐶",
    "dog": "🐕",
    "guide dog": "🦮",
    "service dog": "🐕‍🦺",
    "poodle": "🐩",
    "wolf": "🐺",
    "fox": "🦊",
    "raccoon": "🦝",
    "cat face": "🐱",
    "cat": "🐈",
    "lion": "🦁",
    "tiger face": "🐯",
    "tiger": "🐅",
    "leopard": "🐆",
    "horse face": "🐴",
    "horse": "🐎",
    "unicorn": "🦄",
    "zebra": "🦓",
    "deer": "🦌",
    "bison": "🦬",
    "cow face": "🐮",
    "ox": "🐂",
    "water buffalo": "🐃",
    "cow": "🐄",
    "pig face": "🐷",
    "pig": "🐖",
    "boar": "🐗",
    "pig nose": "🐽",
    "ram": "🐏",
    "ewe": "🐑",
    "goat": "🐐",
    "camel": "🐪",
    "two-hump camel": "🐫",
    "llama": "🦙",
    "giraffe": "🦒",
    "elephant": "🐘",
    "mammoth": "🦣",
    "rhinoceros": "🦏",
    "hippopotamus": "🦛",
    "mouse face": "🐭",
    "mouse": "🐁",
    "rat": "🐀",
    "hamster": "🐹",
    "rabbit face": "🐰",
    "rabbit": "🐇",
    "chipmunk": "🐿️",
    "beaver": "🦫",
    "hedgehog": "🦔",
    "bat": "🦇",
    "bear": "🐻",
    "koala": "🐨",
    "panda": "🐼",
    "sloth": "🦥",
    "otter": "🦦",
    "skunk": "🦨",
    "kangaroo": "🦘",
    "badger": "🦡",
    "paw prints": "🐾",
    "turkey": "🦃",
    "chicken": "🐔",
    "rooster": "🐓",
    "hatching chick": "🐣",
    "baby chick": "🐤",
    "front-facing baby chick": "🐥",
    "bird": "🐦",
    "penguin": "🐧",
    "dove": "🕊️",
    "eagle": "🦅",
    "duck": "🦆",
    "swan": "🦢",
    "owl": "🦉",
    "dodo": "🦤",
    "feather": "🪶",
    "flamingo": "🦩",
    "peacock": "🦚",
    "parrot": "🦜",
    "frog": "🐸",
    "crocodile": "🐊",
    "turtle": "🐢",
    "lizard": "🦎",
    "snake": "🐍",
    "dragon face": "🐲",
    "dragon": "🐉",
    "sauropod": "🦕",
    "T-Rex": "🦖",
    "spouting whale": "🐳",
    "whale": "🐋",
    "dolphin": "🐬",
    "seal": "🦭",
    "fish": "🐟",
    "tropical fish": "🐠",
    "blowfish": "🐡",
    "shark": "🦈",
    "octopus": "🐙",
    "spiral shell": "🐚",
    "snail": "🐌",
    "butterfly": "🦋",
    "bug": "🐛",
    "ant": "🐜",
    "honeybee": "🐝",
    "beetle": "🪲",
    "lady beetle": "🐞",
    "cricket": "🦗",
    "cockroach": "🪳",
    "spider": "🕷️",
    "spider web": "🕸️",
    "scorpion": "🦂",
    "mosquito": "🦟",
    "fly": "🪰",
    "worm": "🪱",
    "microbe": "🦠",
    "bouquet": "💐",
    "cherry blossom": "🌸",
    "white flower": "💮",
    "rosette": "🏵️",
    "rose": "🌹",
    "wilted flower": "🥀",
    "hibiscus": "🌺",
    "sunflower": "🌻",
    "blossom": "🌼",
    "tulip": "🌷",
    "seedling": "🌱",
    "potted plant": "🪴",
    "evergreen tree": "🌲",
    "deciduous tree": "🌳",
    "palm tree": "🌴",
    "cactus": "🌵",
    "sheaf of rice": "🌾",
    "herb": "🌿",
    "shamrock": "☘️",
    "four leaf clover": "🍀",
    "maple leaf": "🍁",
    "fallen leaf": "🍂",
    "leaf fluttering in wind": "🍃",
    "grapes": "🍇",
    "melon": "🍈",
    "watermelon": "🍉",
    "tangerine": "🍊",
    "lemon": "🍋",
    "banana": "🍌",
    "pineapple": "🍍",
    "mango": "🥭",
    "red apple": "🍎",
    "green apple": "🍏",
    "pear": "🍐",
    "peach": "🍑",
    "cherries": "🍒",
    "strawberry": "🍓",
    "blueberries": "🫐",
    "kiwi fruit": "🥝",
    "tomato": "🍅",
    "olive": "🫒",
    "coconut": "🥥",
    "avocado": "🥑",
    "eggplant": "🍆",
    "potato": "🥔",
    "carrot": "🥕",
    "ear of corn": "🌽",
    "hot pepper": "🌶️",
    "bell pepper": "🫑",
    "cucumber": "🥒",
    "leafy green": "🥬",
    "broccoli": "🥦",
    "garlic": "🧄",
    "onion": "🧅",
    "mushroom": "🍄",
    "peanuts": "🥜",
    "chestnut": "🌰",
    "bread": "🍞",
    "croissant": "🥐",
    "baguette bread": "🥖",
    "flatbread": "🫓",
    "pretzel": "🥨",
    "bagel": "🥯",
    "pancakes": "🥞",
    "waffle": "🧇",
    "cheese wedge": "🧀",
    "meat on bone": "🍖",
    "poultry leg": "🍗",
    "cut of meat": "🥩",
    "bacon": "🥓",
    "hamburger": "🍔",
    "french fries": "🍟",
    "pizza": "🍕",
    "hot dog": "🌭",
    "sandwich": "🥪",
    "taco": "🌮",
    "burrito": "🌯",
    "tamale": "🫔",
    "stuffed flatbread": "🥙",
    "falafel": "🧆",
    "egg": "🥚",
    "cooking": "🍳",
    "shallow pan of food": "🥘",
    "pot of food": "🍲",
    "fondue": "🫕",
    "bowl with spoon": "🥣",
    "green salad": "🥗",
    "popcorn": "🍿",
    "butter": "🧈",
    "salt": "🧂",
    "canned food": "🥫",
    "bento box": "🍱",
    "rice cracker": "🍘",
    "rice ball": "🍙",
    "cooked rice": "🍚",
    "curry rice": "🍛",
    "steaming bowl": "🍜",
    "spaghetti": "🍝",
    "roasted sweet potato": "🍠",
    "oden": "🍢",
    "sushi": "🍣",
    "fried shrimp": "🍤",
    "fish cake with swirl": "🍥",
    "moon cake": "🥮",
    "dango": "🍡",
    "dumpling": "🥟",
    "fortune cookie": "🥠",
    "takeout box": "🥡",
    "crab": "🦀",
    "lobster": "🦞",
    "shrimp": "🦐",
    "squid": "🦑",
    "oyster": "🦪",
    "soft ice cream": "🍦",
    "shaved ice": "🍧",
    "ice cream": "🍨",
    "doughnut": "🍩",
    "cookie": "🍪",
    "birthday cake": "🎂",
    "shortcake": "🍰",
    "cupcake": "🧁",
    "pie": "🥧",
    "chocolate bar": "🍫",
    "candy": "🍬",
    "lollipop": "🍭",
    "custard": "🍮",
    "honey pot": "🍯",
    "baby bottle": "🍼",
    "glass of milk": "🥛",
    "hot beverage": "☕",
    "teapot": "🫖",
    "teacup without handle": "🍵",
    "sake": "🍶",
    "bottle with popping cork": "🍾",
    "wine glass": "🍷",
    "cocktail glass": "🍸",
    "tropical drink": "🍹",
    "beer mug": "🍺",
    "clinking beer mugs": "🍻",
    "clinking glasses": "🥂",
    "tumbler glass": "🥃",
    "cup with straw": "🥤",
    "bubble tea": "🧋",
    "beverage box": "🧃",
    "mate": "🧉",
    "ice": "🧊",
    "chopsticks": "🥢",
    "fork and knife with plate": "🍽️",
    "fork and knife": "🍴",
    "spoon": "🥄",
    "kitchen knife": "🔪",
    "amphora": "🏺",
    "globe showing Europe-Africa": "🌍",
    "globe showing Americas": "🌎",
    "globe showing Asia-Australia": "🌏",
    "globe with meridians": "🌐",
    "world map": "🗺️",
    "map of Japan": "🗾",
    "compass": "🧭",
    "snow-capped mountain": "🏔️",
    "mountain": "⛰️",
    "volcano": "🌋",
    "mount fuji": "🗻",
    "camping": "🏕️",
    "beach with umbrella": "🏖️",
    "desert": "🏜️",
    "desert island": "🏝️",
    "national park": "🏞️",
    "stadium": "🏟️",
    "classical building": "🏛️",
    "building construction": "🏗️",
    "brick": "🧱",
    "rock": "🪨",
    "wood": "🪵",
    "hut": "🛖",
    "houses": "🏘️",
    "derelict house": "🏚️",
    "house": "🏠",
    "house with garden": "🏡",
    "office building": "🏢",
    "Japanese post office": "🏣",
    "post office": "🏤",
    "hospital": "🏥",
    "bank": "🏦",
    "hotel": "🏨",
    "love hotel": "🏩",
    "convenience store": "🏪",
    "school": "🏫",
    "department store": "🏬",
    "factory": "🏭",
    "Japanese castle": "🏯",
    "castle": "🏰",
    "wedding": "💒",
    "Tokyo tower": "🗼",
    "Statue of Liberty": "🗽",
    "church": "⛪",
    "mosque": "🕌",
    "hindu temple": "🛕",
    "synagogue": "🕍",
    "shinto shrine": "⛩️",
    "kaaba": "🕋",
    "fountain": "⛲",
    "tent": "⛺",
    "foggy": "🌁",
    "night with stars": "🌃",
    "cityscape": "🏙️",
    "sunrise over mountains": "🌄",
    "sunrise": "🌅",
    "cityscape at dusk": "🌆",
    "sunset": "🌇",
    "bridge at night": "🌉",
    "hot springs": "♨️",
    "carousel horse": "🎠",
    "ferris wheel": "🎡",
    "roller coaster": "🎢",
    "barber pole": "💈",
    "circus tent": "🎪",
    "locomotive": "🚂",
    "railway car": "🚃",
    "high-speed train": "🚄",
    "bullet train": "🚅",
    "train": "🚆",
    "metro": "🚇",
    "light rail": "🚈",
    "station": "🚉",
    "tram": "🚊",
    "monorail": "🚝",
    "mountain railway": "🚞",
    "tram car": "🚋",
    "bus": "🚌",
    "oncoming bus": "🚍",
    "trolleybus": "🚎",
    "minibus": "🚐",
    "ambulance": "🚑",
    "fire engine": "🚒",
    "police car": "🚓",
    "oncoming police car": "🚔",
    "taxi": "🚕",
    "oncoming taxi": "🚖",
    "automobile": "🚗",
    "oncoming automobile": "🚘",
    "sport utility vehicle": "🚙",
    "pickup truck": "🛻",
    "delivery truck": "🚚",
    "articulated lorry": "🚛",
    "tractor": "🚜",
    "racing car": "🏎️",
    "motorcycle": "🏍️",
    "motor scooter": "🛵",
    "manual wheelchair": "🦽",
    "motorized wheelchair": "🦼",
    "auto rickshaw": "🛺",
    "bicycle": "🚲",
    "kick scooter": "🛴",
    "skateboard": "🛹",
    "roller skate": "🛼",
    "bus stop": "🚏",
    "motorway": "🛣️",
    "railway track": "🛤️",
    "oil drum": "🛢️",
    "fuel pump": "⛽",
    "police car light": "🚨",
    "horizontal traffic light": "🚥",
    "vertical traffic light": "🚦",
    "stop sign": "🛑",
    "construction": "🚧",
    "anchor": "⚓",
    "sailboat": "⛵",
    "canoe": "🛶",
    "speedboat": "🚤",
    "passenger ship": "🛳️",
    "ferry": "⛴️",
    "motor boat": "🛥️",
    "ship": "🚢",
    "airplane": "✈️",
    "small airplane": "🛩️",
    "airplane departure": "🛫",
    "airplane arrival": "🛬",
    "parachute": "🪂",
    "seat": "💺",
    "helicopter": "🚁",
    "suspension railway": "🚟",
    "mountain cableway": "🚠",
    "aerial tramway": "🚡",
    "satellite": "🛰️",
    "rocket": "🚀",
    "flying saucer": "🛸",
    "bellhop bell": "🛎️",
    "luggage": "🧳",
    "hourglass done": "⌛",
    "hourglass not done": "⏳",
    "watch": "⌚",
    "alarm clock": "⏰",
    "stopwatch": "⏱️",
    "timer clock": "⏲️",
    "mantelpiece clock": "🕰️",
    "twelve o’clock": "🕛",
    "twelve-thirty": "🕧",
    "one o’clock": "🕐",
    "one-thirty": "🕜",
    "two o’clock": "🕑",
    "two-thirty": "🕝",
    "three o’clock": "🕒",
    "three-thirty": "🕞",
    "four o’clock": "🕓",
    "four-thirty": "🕟",
    "five o’clock": "🕔",
    "five-thirty": "🕠",
    "six o’clock": "🕕",
    "six-thirty": "🕡",
    "seven o’clock": "🕖",
    "seven-thirty": "🕢",
    "eight o’clock": "🕗",
    "eight-thirty": "🕣",
    "nine o’clock": "🕘",
    "nine-thirty": "🕤",
    "ten o’clock": "🕙",
    "ten-thirty": "🕥",
    "eleven o’clock": "🕚",
    "eleven-thirty": "🕦",
    "new moon": "🌑",
    "waxing crescent moon": "🌒",
    "first quarter moon": "🌓",
    "waxing gibbous moon": "🌔",
    "full moon": "🌕",
    "waning gibbous moon": "🌖",
    "last quarter moon": "🌗",
    "waning crescent moon": "🌘",
    "crescent moon": "🌙",
    "new moon face": "🌚",
    "first quarter moon face": "🌛",
    "last quarter moon face": "🌜",
    "thermometer": "🌡️",
    "sun": "☀️",
    "full moon face": "🌝",
    "sun with face": "🌞",
    "ringed planet": "🪐",
    "star": "⭐",
    "glowing star": "🌟",
    "shooting star": "🌠",
    "milky way": "🌌",
    "cloud": "☁️",
    "sun behind cloud": "⛅",
    "cloud with lightning and rain": "⛈️",
    "sun behind small cloud": "🌤️",
    "sun behind large cloud": "🌥️",
    "sun behind rain cloud": "🌦️",
    "cloud with rain": "🌧️",
    "cloud with snow": "🌨️",
    "cloud with lightning": "🌩️",
    "tornado": "🌪️",
    "fog": "🌫️",
    "wind face": "🌬️",
    "cyclone": "🌀",
    "rainbow": "🌈",
    "closed umbrella": "🌂",
    "umbrella": "☂️",
    "umbrella with rain drops": "☔",
    "umbrella on ground": "⛱️",
    "high voltage": "⚡",
    "snowflake": "❄️",
    "snowman": "☃️",
    "snowman without snow": "⛄",
    "comet": "☄️",
    "fire": "🔥",
    "droplet": "💧",
    "water wave": "🌊",
    "jack-o-lantern": "🎃",
    "Christmas tree": "🎄",
    "fireworks": "🎆",
    "sparkler": "🎇",
    "firecracker": "🧨",
    "sparkles": "✨",
    "balloon": "🎈",
    "party popper": "🎉",
    "confetti ball": "🎊",
    "tanabata tree": "🎋",
    "pine decoration": "🎍",
    "Japanese dolls": "🎎",
    "carp streamer": "🎏",
    "wind chime": "🎐",
    "moon viewing ceremony": "🎑",
    "red envelope": "🧧",
    "ribbon": "🎀",
    "wrapped gift": "🎁",
    "reminder ribbon": "🎗️",
    "admission tickets": "🎟️",
    "ticket": "🎫",
    "military medal": "🎖️",
    "trophy": "🏆",
    "sports medal": "🏅",
    "1st place medal": "🥇",
    "2nd place medal": "🥈",
    "3rd place medal": "🥉",
    "soccer ball": "⚽",
    "baseball": "⚾",
    "softball": "🥎",
    "basketball": "🏀",
    "volleyball": "🏐",
    "american football": "🏈",
    "rugby football": "🏉",
    "tennis": "🎾",
    "flying disc": "🥏",
    "bowling": "🎳",
    "cricket game": "🏏",
    "field hockey": "🏑",
    "ice hockey": "🏒",
    "lacrosse": "🥍",
    "ping pong": "🏓",
    "badminton": "🏸",
    "boxing glove": "🥊",
    "martial arts uniform": "🥋",
    "goal net": "🥅",
    "flag in hole": "⛳",
    "ice skate": "⛸️",
    "fishing pole": "🎣",
    "diving mask": "🤿",
    "running shirt": "🎽",
    "skis": "🎿",
    "sled": "🛷",
    "curling stone": "🥌",
    "direct hit": "🎯",
    "yo-yo": "🪀",
    "kite": "🪁",
    "pool 8 ball": "🎱",
    "crystal ball": "🔮",
    "magic wand": "🪄",
    "nazar amulet": "🧿",
    "video game": "🎮",
    "joystick": "🕹️",
    "slot machine": "🎰",
    "game die": "🎲",
    "puzzle piece": "🧩",
    "teddy bear": "🧸",
    "piñata": "🪅",
    "nesting dolls": "🪆",
    "spade suit": "♠️",
    "heart suit": "♥️",
    "diamond suit": "♦️",
    "club suit": "♣️",
    "chess pawn": "♟️",
    "joker": "🃏",
    "mahjong red dragon": "🀄",
    "flower playing cards": "🎴",
    "performing arts": "🎭",
    "framed picture": "🖼️",
    "artist palette": "🎨",
    "thread": "🧵",
    "sewing needle": "🪡",
    "yarn": "🧶",
    "knot": "🪢",
    "glasses": "👓",
    "sunglasses": "🕶️",
    "goggles": "🥽",
    "lab coat": "🥼",
    "safety vest": "🦺",
    "necktie": "👔",
    "t-shirt": "👕",
    "jeans": "👖",
    "scarf": "🧣",
    "gloves": "🧤",
    "coat": "🧥",
    "socks": "🧦",
    "dress": "👗",
    "kimono": "👘",
    "sari": "🥻",
    "one-piece swimsuit": "🩱",
    "briefs": "🩲",
    "shorts": "🩳",
    "bikini": "👙",
    "woman’s clothes": "👚",
    "purse": "👛",
    "handbag": "👜",
    "clutch bag": "👝",
    "shopping bags": "🛍️",
    "backpack": "🎒",
    "thong sandal": "🩴",
    "man’s shoe": "👞",
    "running shoe": "👟",
    "hiking boot": "🥾",
    "flat shoe": "🥿",
    "high-heeled shoe": "👠",
    "woman’s sandal": "👡",
    "ballet shoes": "🩰",
    "woman’s boot": "👢",
    "crown": "👑",
    "woman’s hat": "👒",
    "top hat": "🎩",
    "graduation cap": "🎓",
    "billed cap": "🧢",
    "military helmet": "🪖",
    "rescue worker’s helmet": "⛑️",
    "prayer beads": "📿",
    "lipstick": "💄",
    "ring": "💍",
    "gem stone": "💎",
    "muted speaker": "🔇",
    "speaker low volume": "🔈",
    "speaker medium volume": "🔉",
    "speaker high volume": "🔊",
    "loudspeaker": "📢",
    "megaphone": "📣",
    "postal horn": "📯",
    "bell": "🔔",
    "bell with slash": "🔕",
    "musical score": "🎼",
    "musical note": "🎵",
    "musical notes": "🎶",
    "studio microphone": "🎙️",
    "level slider": "🎚️",
    "control knobs": "🎛️",
    "microphone": "🎤",
    "headphone": "🎧",
    "radio": "📻",
    "saxophone": "🎷",
    "accordion": "🪗",
    "guitar": "🎸",
    "musical keyboard": "🎹",
    "trumpet": "🎺",
    "violin": "🎻",
    "banjo": "🪕",
    "drum": "🥁",
    "long drum": "🪘",
    "mobile phone": "📱",
    "mobile phone with arrow": "📲",
    "telephone": "☎️",
    "telephone receiver": "📞",
    "pager": "📟",
    "fax machine": "📠",
    "battery": "🔋",
    "electric plug": "🔌",
    "laptop": "💻",
    "desktop computer": "🖥️",
    "printer": "🖨️",
    "keyboard": "⌨️",
    "computer mouse": "🖱️",
    "trackball": "🖲️",
    "computer disk": "💽",
    "floppy disk": "💾",
    "optical disk": "💿",
    "dvd": "📀",
    "abacus": "🧮",
    "movie camera": "🎥",
    "film frames": "🎞️",
    "film projector": "📽️",
    "clapper board": "🎬",
    "television": "📺",
    "camera": "📷",
    "camera with flash": "📸",
    "video camera": "📹",
    "videocassette": "📼",
    "magnifying glass tilted left": "🔍",
    "magnifying glass tilted right": "🔎",
    "candle": "🕯️",
    "light bulb": "💡",
    "flashlight": "🔦",
    "red paper lantern": "🏮",
    "diya lamp": "🪔",
    "notebook with decorative cover": "📔",
    "closed book": "📕",
    "open book": "📖",
    "green book": "📗",
    "blue book": "📘",
    "orange book": "📙",
    "books": "📚",
    "notebook": "📓",
    "ledger": "📒",
    "page with curl": "📃",
    "scroll": "📜",
    "page facing up": "📄",
    "newspaper": "📰",
    "rolled-up newspaper": "🗞️",
    "bookmark tabs": "📑",
    "bookmark": "🔖",
    "label": "🏷️",
    "money bag": "💰",
    "coin": "🪙",
    "yen banknote": "💴",
    "dollar banknote": "💵",
    "euro banknote": "💶",
    "pound banknote": "💷",
    "money with wings": "💸",
    "credit card": "💳",
    "receipt": "🧾",
    "chart increasing with yen": "💹",
    "envelope": "✉️",
    "e-mail": "📧",
    "incoming envelope": "📨",
    "envelope with arrow": "📩",
    "outbox tray": "📤",
    "inbox tray": "📥",
    "package": "📦",
    "closed mailbox with raised flag": "📫",
    "closed mailbox with lowered flag": "📪",
    "open mailbox with raised flag": "📬",
    "open mailbox with lowered flag": "📭",
    "postbox": "📮",
    "ballot box with ballot": "🗳️",
    "pencil": "✏️",
    "black nib": "✒️",
    "fountain pen": "🖋️",
    "pen": "🖊️",
    "paintbrush": "🖌️",
    "crayon": "🖍️",
    "memo": "📝",
    "briefcase": "💼",
    "file folder": "📁",
    "open file folder": "📂",
    "card index dividers": "🗂️",
    "calendar": "📅",
    "tear-off calendar": "📆",
    "spiral notepad": "🗒️",
    "spiral calendar": "🗓️",
    "card index": "📇",
    "chart increasing": "📈",
    "chart decreasing": "📉",
    "bar chart": "📊",
    "clipboard": "📋",
    "pushpin": "📌",
    "round pushpin": "📍",
    "paperclip": "📎",
    "linked paperclips": "🖇️",
    "straight ruler": "📏",
    "triangular ruler": "📐",
    "scissors": "✂️",
    "card file box": "🗃️",
    "file cabinet": "🗄️",
    "wastebasket": "🗑️",
    "locked": "🔒",
    "unlocked": "🔓",
    "locked with pen": "🔏",
    "locked with key": "🔐",
    "key": "🔑",
    "old key": "🗝️",
    "hammer": "🔨",
    "axe": "🪓",
    "pick": "⛏️",
    "hammer and pick": "⚒️",
    "hammer and wrench": "🛠️",
    "dagger": "🗡️",
    "crossed swords": "⚔️",
    "pistol": "🔫",
    "boomerang": "🪃",
    "bow and arrow": "🏹",
    "shield": "🛡️",
    "carpentry saw": "🪚",
    "wrench": "🔧",
    "screwdriver": "🪛",
    "nut and bolt": "🔩",
    "gear": "⚙️",
    "clamp": "🗜️",
    "balance scale": "⚖️",
    "white cane": "🦯",
    "link": "🔗",
    "chains": "⛓️",
    "hook": "🪝",
    "toolbox": "🧰",
    "magnet": "🧲",
    "ladder": "🪜",
    "alembic": "⚗️",
    "test tube": "🧪",
    "petri dish": "🧫",
    "dna": "🧬",
    "microscope": "🔬",
    "telescope": "🔭",
    "satellite antenna": "📡",
    "syringe": "💉",
    "drop of blood": "🩸",
    "pill": "💊",
    "adhesive bandage": "🩹",
    "stethoscope": "🩺",
    "door": "🚪",
    "elevator": "🛗",
    "mirror": "🪞",
    "window": "🪟",
    "bed": "🛏️",
    "couch and lamp": "🛋️",
    "chair": "🪑",
    "toilet": "🚽",
    "plunger": "🪠",
    "shower": "🚿",
    "bathtub": "🛁",
    "mouse trap": "🪤",
    "razor": "🪒",
    "lotion bottle": "🧴",
    "safety pin": "🧷",
    "broom": "🧹",
    "basket": "🧺",
    "roll of paper": "🧻",
    "bucket": "🪣",
    "soap": "🧼",
    "toothbrush": "🪥",
    "sponge": "🧽",
    "fire extinguisher": "🧯",
    "shopping cart": "🛒",
    "cigarette": "🚬",
    "coffin": "⚰️",
    "headstone": "🪦",
    "funeral urn": "⚱️",
    "moai": "🗿",
    "placard": "🪧",
    "ATM sign": "🏧",
    "litter in bin sign": "🚮",
    "potable water": "🚰",
    "wheelchair symbol": "♿",
    "men’s room": "🚹",
    "women’s room": "🚺",
    "restroom": "🚻",
    "baby symbol": "🚼",
    "water closet": "🚾",
    "passport control": "🛂",
    "customs": "🛃",
    "baggage claim": "🛄",
    "left luggage": "🛅",
    "warning": "⚠️",
    "children crossing": "🚸",
    "no entry": "⛔",
    "prohibited": "🚫",
    "no bicycles": "🚳",
    "no smoking": "🚭",
    "no littering": "🚯",
    "non-potable water": "🚱",
    "no pedestrians": "🚷",
    "no mobile phones": "📵",
    "no one under eighteen": "🔞",
    "radioactive": "☢️",
    "biohazard": "☣️",
    "up arrow": "⬆️",
    "up-right arrow": "↗️",
    "right arrow": "➡️",
    "down-right arrow": "↘️",
    "down arrow": "⬇️",
    "down-left arrow": "↙️",
    "left arrow": "⬅️",
    "up-left arrow": "↖️",
    "up-down arrow": "↕️",
    "left-right arrow": "↔️",
    "right arrow curving left": "↩️",
    "left arrow curving right": "↪️",
    "right arrow curving up": "⤴️",
    "right arrow curving down": "⤵️",
    "clockwise vertical arrows": "🔃",
    "counterclockwise arrows button": "🔄",
    "BACK arrow": "🔙",
    "END arrow": "🔚",
    "ON! arrow": "🔛",
    "SOON arrow": "🔜",
    "TOP arrow": "🔝",
    "place of worship": "🛐",
    "atom symbol": "⚛️",
    "om": "🕉️",
    "star of David": "✡️",
    "wheel of dharma": "☸️",
    "yin yang": "☯️",
    "latin cross": "✝️",
    "orthodox cross": "☦️",
    "star and crescent": "☪️",
    "peace symbol": "☮️",
    "menorah": "🕎",
    "dotted six-pointed star": "🔯",
    "Aries": "♈",
    "Taurus": "♉",
    "Gemini": "♊",
    "Cancer": "♋",
    "Leo": "♌",
    "Virgo": "♍",
    "Libra": "♎",
    "Scorpio": "♏",
    "Sagittarius": "♐",
    "Capricorn": "♑",
    "Aquarius": "♒",
    "Pisces": "♓",
    "Ophiuchus": "⛎",
    "shuffle tracks button": "🔀",
    "repeat button": "🔁",
    "repeat single button": "🔂",
    "play button": "▶️",
    "fast-forward button": "⏩",
    "next track button": "⏭️",
    "play or pause button": "⏯️",
    "reverse button": "◀️",
    "fast reverse button": "⏪",
    "last track button": "⏮️",
    "upwards button": "🔼",
    "fast up button": "⏫",
    "downwards button": "🔽",
    "fast down button": "⏬",
    "pause button": "⏸️",
    "stop button": "⏹️",
    "record button": "⏺️",
    "eject button": "⏏️",
    "cinema": "🎦",
    "dim button": "🔅",
    "bright button": "🔆",
    "antenna bars": "📶",
    "vibration mode": "📳",
    "mobile phone off": "📴",
    "female sign": "♀️",
    "male sign": "♂️",
    "transgender symbol": "⚧️",
    "multiply": "✖️",
    "plus": "➕",
    "minus": "➖",
    "divide": "➗",
    "infinity": "♾️",
    "double exclamation mark": "‼️",
    "exclamation question mark": "⁉️",
    "question mark": "❓",
    "white question mark": "❔",
    "white exclamation mark": "❕",
    "exclamation mark": "❗",
    "wavy dash": "〰️",
    "currency exchange": "💱",
    "heavy dollar sign": "💲",
    "medical symbol": "⚕️",
    "recycling symbol": "♻️",
    "fleur-de-lis": "⚜️",
    "trident emblem": "🔱",
    "name badge": "📛",
    "Japanese symbol for beginner": "🔰",
    "hollow red circle": "⭕",
    "check mark button": "✅",
    "check box with check": "☑️",
    "check mark": "✔️",
    "cross mark": "❌",
    "cross mark button": "❎",
    "curly loop": "➰",
    "double curly loop": "➿",
    "part alternation mark": "〽️",
    "eight-spoked asterisk": "✳️",
    "eight-pointed star": "✴️",
    "sparkle": "❇️",
    "copyright": "©️",
    "registered": "®️",
    "trade mark": "™️",
    "keycap: *": "*️⃣",
    "keycap: 0": "0️⃣",
    "keycap: 1": "1️⃣",
    "keycap: 2": "2️⃣",
    "keycap: 3": "3️⃣",
    "keycap: 4": "4️⃣",
    "keycap: 5": "5️⃣",
    "keycap: 6": "6️⃣",
    "keycap: 7": "7️⃣",
    "keycap: 8": "8️⃣",
    "keycap: 9": "9️⃣",
    "keycap: 10": "🔟",
    "input latin uppercase": "🔠",
    "input latin lowercase": "🔡",
    "input numbers": "🔢",
    "input symbols": "🔣",
    "input latin letters": "🔤",
    "A button (blood type)": "🅰️",
    "AB button (blood type)": "🆎",
    "B button (blood type)": "🅱️",
    "CL button": "🆑",
    "COOL button": "🆒",
    "FREE button": "🆓",
    "information": "ℹ️",
    "ID button": "🆔",
    "circled M": "Ⓜ️",
    "NEW button": "🆕",
    "NG button": "🆖",
    "O button (blood type)": "🅾️",
    "OK button": "🆗",
    "P button": "🅿️",
    "SOS button": "🆘",
    "UP! button": "🆙",
    "VS button": "🆚",
    "Japanese “here” button": "🈁",
    "Japanese “service charge” button": "🈂️",
    "Japanese “monthly amount” button": "🈷️",
    "Japanese “not free of charge” button": "🈶",
    "Japanese “reserved” button": "🈯",
    "Japanese “bargain” button": "🉐",
    "Japanese “discount” button": "🈹",
    "Japanese “free of charge” button": "🈚",
    "Japanese “prohibited” button": "🈲",
    "Japanese “acceptable” button": "🉑",
    "Japanese “application” button": "🈸",
    "Japanese “passing grade” button": "🈴",
    "Japanese “vacancy” button": "🈳",
    "Japanese “congratulations” button": "㊗️",
    "Japanese “secret” button": "㊙️",
    "Japanese “open for business” button": "🈺",
    "Japanese “no vacancy” button": "🈵",
    "red circle": "🔴",
    "orange circle": "🟠",
    "yellow circle": "🟡",
    "green circle": "🟢",
    "blue circle": "🔵",
    "purple circle": "🟣",
    "brown circle": "🟤",
    "black circle": "⚫",
    "white circle": "⚪",
    "red square": "🟥",
    "orange square": "🟧",
    "yellow square": "🟨",
    "green square": "🟩",
    "blue square": "🟦",
    "purple square": "🟪",
    "brown square": "🟫",
    "black large square": "⬛",
    "white large square": "⬜",
    "black medium square": "◼️",
    "white medium square": "◻️",
    "black medium-small square": "◾",
    "white medium-small square": "◽",
    "black small square": "▪️",
    "white small square": "▫️",
    "large orange diamond": "🔶",
    "large blue diamond": "🔷",
    "small orange diamond": "🔸",
    "small blue diamond": "🔹",
    "red triangle pointed up": "🔺",
    "red triangle pointed down": "🔻",
    "diamond with a dot": "💠",
    "radio button": "🔘",
    "white square button": "🔳",
    "black square button": "🔲",
    "chequered flag": "🏁",
    "triangular flag": "🚩",
    "crossed flags": "🎌",
    "black flag": "🏴",
    "white flag": "🏳️",
    "rainbow flag": "🏳️‍🌈",
    "transgender flag": "🏳️‍⚧️",
    "pirate flag": "🏴‍☠️",
    "flag: Ascension Island": "🇦🇨",
    "flag: Andorra": "🇦🇩",
    "flag: United Arab Emirates": "🇦🇪",
    "flag: Afghanistan": "🇦🇫",
    "flag: Antigua & Barbuda": "🇦🇬",
    "flag: Anguilla": "🇦🇮",
    "flag: Albania": "🇦🇱",
    "flag: Armenia": "🇦🇲",
    "flag: Angola": "🇦🇴",
    "flag: Antarctica": "🇦🇶",
    "flag: Argentina": "🇦🇷",
    "flag: American Samoa": "🇦🇸",
    "flag: Austria": "🇦🇹",
    "flag: Australia": "🇦🇺",
    "flag: Aruba": "🇦🇼",
    "flag: Åland Islands": "🇦🇽",
    "flag: Azerbaijan": "🇦🇿",
    "flag: Bosnia & Herzegovina": "🇧🇦",
    "flag: Barbados": "🇧🇧",
    "flag: Bangladesh": "🇧🇩",
    "flag: Belgium": "🇧🇪",
    "flag: Burkina Faso": "🇧🇫",
    "flag: Bulgaria": "🇧🇬",
    "flag: Bahrain": "🇧🇭",
    "flag: Burundi": "🇧🇮",
    "flag: Benin": "🇧🇯",
    "flag: St. Barthélemy": "🇧🇱",
    "flag: Bermuda": "🇧🇲",
    "flag: Brunei": "🇧🇳",
    "flag: Bolivia": "🇧🇴",
    "flag: Caribbean Netherlands": "🇧🇶",
    "flag: Brazil": "🇧🇷",
    "flag: Bahamas": "🇧🇸",
    "flag: Bhutan": "🇧🇹",
    "flag: Bouvet Island": "🇧🇻",
    "flag: Botswana": "🇧🇼",
    "flag: Belarus": "🇧🇾",
    "flag: Belize": "🇧🇿",
    "flag: Canada": "🇨🇦",
    "flag: Cocos (Keeling) Islands": "🇨🇨",
    "flag: Congo - Kinshasa": "🇨🇩",
    "flag: Central African Republic": "🇨🇫",
    "flag: Congo - Brazzaville": "🇨🇬",
    "flag: Switzerland": "🇨🇭",
    "flag: Côte d’Ivoire": "🇨🇮",
    "flag: Cook Islands": "🇨🇰",
    "flag: Chile": "🇨🇱",
    "flag: Cameroon": "🇨🇲",
    "flag: China": "🇨🇳",
    "flag: Colombia": "🇨🇴",
    "flag: Clipperton Island": "🇨🇵",
    "flag: Costa Rica": "🇨🇷",
    "flag: Cuba": "🇨🇺",
    "flag: Cape Verde": "🇨🇻",
    "flag: Curaçao": "🇨🇼",
    "flag: Christmas Island": "🇨🇽",
    "flag: Cyprus": "🇨🇾",
    "flag: Czechia": "🇨🇿",
    "flag: Germany": "🇩🇪",
    "flag: Diego Garcia": "🇩🇬",
    "flag: Djibouti": "🇩🇯",
    "flag: Denmark": "🇩🇰",
    "flag: Dominica": "🇩🇲",
    "flag: Dominican Republic": "🇩🇴",
    "flag: Algeria": "🇩🇿",
    "flag: Ceuta & Melilla": "🇪🇦",
    "flag: Ecuador": "🇪🇨",
    "flag: Estonia": "🇪🇪",
    "flag: Egypt": "🇪🇬",
    "flag: Western Sahara": "🇪🇭",
    "flag: Eritrea": "🇪🇷",
    "flag: Spain": "🇪🇸",
    "flag: Ethiopia": "🇪🇹",
    "flag: European Union": "🇪🇺",
    "flag: Finland": "🇫🇮",
    "flag: Fiji": "🇫🇯",
    "flag: Falkland Islands": "🇫🇰",
    "flag: Micronesia": "🇫🇲",
    "flag: Faroe Islands": "🇫🇴",
    "flag: France": "🇫🇷",
    "flag: Gabon": "🇬🇦",
    "flag: United Kingdom": "🇬🇧",
    "flag: Grenada": "🇬🇩",
    "flag: Georgia": "🇬🇪",
    "flag: French Guiana": "🇬🇫",
    "flag: Guernsey": "🇬🇬",
    "flag: Ghana": "🇬🇭",
    "flag: Gibraltar": "🇬🇮",
    "flag: Greenland": "🇬🇱",
    "flag: Gambia": "🇬🇲",
    "flag: Guinea": "🇬🇳",
    "flag: Guadeloupe": "🇬🇵",
    "flag: Equatorial Guinea": "🇬🇶",
    "flag: Greece": "🇬🇷",
    "flag: South Georgia & South Sandwich Islands": "🇬🇸",
    "flag: Guatemala": "🇬🇹",
    "flag: Guam": "🇬🇺",
    "flag: Guinea-Bissau": "🇬🇼",
    "flag: Guyana": "🇬🇾",
    "flag: Hong Kong SAR China": "🇭🇰",
    "flag: Heard & McDonald Islands": "🇭🇲",
    "flag: Honduras": "🇭🇳",
    "flag: Croatia": "🇭🇷",
    "flag: Haiti": "🇭🇹",
    "flag: Hungary": "🇭🇺",
    "flag: Canary Islands": "🇮🇨",
    "flag: Indonesia": "🇮🇩",
    "flag: Ireland": "🇮🇪",
    "flag: Israel": "🇮🇱",
    "flag: Isle of Man": "🇮🇲",
    "flag: India": "🇮🇳",
    "flag: British Indian Ocean Territory": "🇮🇴",
    "flag: Iraq": "🇮🇶",
    "flag: Iran": "🇮🇷",
    "flag: Iceland": "🇮🇸",
    "flag: Italy": "🇮🇹",
    "flag: Jersey": "🇯🇪",
    "flag: Jamaica": "🇯🇲",
    "flag: Jordan": "🇯🇴",
    "flag: Japan": "🇯🇵",
    "flag: Kenya": "🇰🇪",
    "flag: Kyrgyzstan": "🇰🇬",
    "flag: Cambodia": "🇰🇭",
    "flag: Kiribati": "🇰🇮",
    "flag: Comoros": "🇰🇲",
    "flag: St. Kitts & Nevis": "🇰🇳",
    "flag: North Korea": "🇰🇵",
    "flag: South Korea": "🇰🇷",
    "flag: Kuwait": "🇰🇼",
    "flag: Cayman Islands": "🇰🇾",
    "flag: Kazakhstan": "🇰🇿",
    "flag: Laos": "🇱🇦",
    "flag: Lebanon": "🇱🇧",
    "flag: St. Lucia": "🇱🇨",
    "flag: Liechtenstein": "🇱🇮",
    "flag: Sri Lanka": "🇱🇰",
    "flag: Liberia": "🇱🇷",
    "flag: Lesotho": "🇱🇸",
    "flag: Lithuania": "🇱🇹",
    "flag: Luxembourg": "🇱🇺",
    "flag: Latvia": "🇱🇻",
    "flag: Libya": "🇱🇾",
    "flag: Morocco": "🇲🇦",
    "flag: Monaco": "🇲🇨",
    "flag: Moldova": "🇲🇩",
    "flag: Montenegro": "🇲🇪",
    "flag: St. Martin": "🇲🇫",
    "flag: Madagascar": "🇲🇬",
    "flag: Marshall Islands": "🇲🇭",
    "flag: North Macedonia": "🇲🇰",
    "flag: Mali": "🇲🇱",
    "flag: Myanmar (Burma)": "🇲🇲",
    "flag: Mongolia": "🇲🇳",
    "flag: Macao SAR China": "🇲🇴",
    "flag: Northern Mariana Islands": "🇲🇵",
    "flag: Martinique": "🇲🇶",
    "flag: Mauritania": "🇲🇷",
    "flag: Montserrat": "🇲🇸",
    "flag: Malta": "🇲🇹",
    "flag: Mauritius": "🇲🇺",
    "flag: Maldives": "🇲🇻",
    "flag: Malawi": "🇲🇼",
    "flag: Mexico": "🇲🇽",
    "flag: Malaysia": "🇲🇾",
    "flag: Mozambique": "🇲🇿",
    "flag: Namibia": "🇳🇦",
    "flag: New Caledonia": "🇳🇨",
    "flag: Niger": "🇳🇪",
    "flag: Norfolk Island": "🇳🇫",
    "flag: Nigeria": "🇳🇬",
    "flag: Nicaragua": "🇳🇮",
    "flag: Netherlands": "🇳🇱",
    "flag: Norway": "🇳🇴",
    "flag: Nepal": "🇳🇵",
    "flag: Nauru": "🇳🇷",
    "flag: Niue": "🇳🇺",
    "flag: New Zealand": "🇳🇿",
    "flag: Oman": "🇴🇲",
    "flag: Panama": "🇵🇦",
    "flag: Peru": "🇵🇪",
    "flag: French Polynesia": "🇵🇫",
    "flag: Papua New Guinea": "🇵🇬",
    "flag: Philippines": "🇵🇭",
    "flag: Pakistan": "🇵🇰",
    "flag: Poland": "🇵🇱",
    "flag: St. Pierre & Miquelon": "🇵🇲",
    "flag: Pitcairn Islands": "🇵🇳",
    "flag: Puerto Rico": "🇵🇷",
    "flag: Palestinian Territories": "🇵🇸",
    "flag: Portugal": "🇵🇹",
    "flag: Palau": "🇵🇼",
    "flag: Paraguay": "🇵🇾",
    "flag: Qatar": "🇶🇦",
    "flag: Réunion": "🇷🇪",
    "flag: Romania": "🇷🇴",
    "flag: Serbia": "🇷🇸",
    "flag: Russia": "🇷🇺",
    "flag: Rwanda": "🇷🇼",
    "flag: Saudi Arabia": "🇸🇦",
    "flag: Solomon Islands": "🇸🇧",
    "flag: Seychelles": "🇸🇨",
    "flag: Sudan": "🇸🇩",
    "flag: Sweden": "🇸🇪",
    "flag: Singapore": "🇸🇬",
    "flag: St. Helena": "🇸🇭",
    "flag: Slovenia": "🇸🇮",
    "flag: Svalbard & Jan Mayen": "🇸🇯",
    "flag: Slovakia": "🇸🇰",
    "flag: Sierra Leone": "🇸🇱",
    "flag: San Marino": "🇸🇲",
    "flag: Senegal": "🇸🇳",
    "flag: Somalia": "🇸🇴",
    "flag: Suriname": "🇸🇷",
    "flag: South Sudan": "🇸🇸",
    "flag: São Tomé & Príncipe": "🇸🇹",
    "flag: El Salvador": "🇸🇻",
    "flag: Sint Maarten": "🇸🇽",
    "flag: Syria": "🇸🇾",
    "flag: Eswatini": "🇸🇿",
    "flag: Tristan da Cunha": "🇹🇦",
    "flag: Turks & Caicos Islands": "🇹🇨",
    "flag: Chad": "🇹🇩",
    "flag: French Southern Territories": "🇹🇫",
    "flag: Togo": "🇹🇬",
    "flag: Thailand": "🇹🇭",
    "flag: Tajikistan": "🇹🇯",
    "flag: Tokelau": "🇹🇰",
    "flag: Timor-Leste": "🇹🇱",
    "flag: Turkmenistan": "🇹🇲",
    "flag: Tunisia": "🇹🇳",
    "flag: Tonga": "🇹🇴",
    "flag: Turkey": "🇹🇷",
    "flag: Trinidad & Tobago": "🇹🇹",
    "flag: Tuvalu": "🇹🇻",
    "flag: Taiwan": "🇹🇼",
    "flag: Tanzania": "🇹🇿",
    "flag: Ukraine": "🇺🇦",
    "flag: Uganda": "🇺🇬",
    "flag: U.S. Outlying Islands": "🇺🇲",
    "flag: United Nations": "🇺🇳",
    "flag: United States": "🇺🇸",
    "flag: Uruguay": "🇺🇾",
    "flag: Uzbekistan": "🇺🇿",
    "flag: Vatican City": "🇻🇦",
    "flag: St. Vincent & Grenadines": "🇻🇨",
    "flag: Venezuela": "🇻🇪",
    "flag: British Virgin Islands": "🇻🇬",
    "flag: U.S. Virgin Islands": "🇻🇮",
    "flag: Vietnam": "🇻🇳",
    "flag: Vanuatu": "🇻🇺",
    "flag: Wallis & Futuna": "🇼🇫",
    "flag: Samoa": "🇼🇸",
    "flag: Kosovo": "🇽🇰",
    "flag: Yemen": "🇾🇪",
    "flag: Mayotte": "🇾🇹",
    "flag: South Africa": "🇿🇦",
    "flag: Zambia": "🇿🇲",
    "flag: Zimbabwe": "🇿🇼",
    "flag: England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "E1.0 grinning face": "😀",
    "E0.6 grinning face with big eyes": "😃",
    "E0.6 grinning face with smiling eyes": "😄",
    "E0.6 beaming face with smiling eyes": "😁",
    "E0.6 grinning squinting face": "😆",
    "E0.6 grinning face with sweat": "😅",
    "E3.0 rolling on the floor laughing": "🤣",
    "E0.6 face with tears of joy": "😂",
    "E1.0 slightly smiling face": "🙂",
    "E1.0 upside-down face": "🙃",
    "E0.6 winking face": "😉",
    "E0.6 smiling face with smiling eyes": "😊",
    "E1.0 smiling face with halo": "😇",
    "E11.0 smiling face with hearts": "🥰",
    "E0.6 smiling face with heart-eyes": "😍",
    "E5.0 star-struck": "🤩",
    "E0.6 face blowing a kiss": "😘",
    "E1.0 kissing face": "😗",
    "E0.6 smiling face": "☺️",
    "E0.6 kissing face with closed eyes": "😚",
    "E1.0 kissing face with smiling eyes": "😙",
    "E13.0 smiling face with tear": "🥲",
    "E0.6 face savoring food": "😋",
    "E1.0 face with tongue": "😛",
    "E0.6 winking face with tongue": "😜",
    "E5.0 zany face": "🤪",
    "E0.6 squinting face with tongue": "😝",
    "E1.0 money-mouth face": "🤑",
    "E1.0 hugging face": "🤗",
    "E5.0 face with hand over mouth": "🤭",
    "E5.0 shushing face": "🤫",
    "E1.0 thinking face": "🤔",
    "E1.0 zipper-mouth face": "🤐",
    "E5.0 face with raised eyebrow": "🤨",
    "E0.7 neutral face": "😐",
    "E1.0 expressionless face": "😑",
    "E1.0 face without mouth": "😶",
    "E0.6 smirking face": "😏",
    "E0.6 unamused face": "😒",
    "E1.0 face with rolling eyes": "🙄",
    "E1.0 grimacing face": "😬",
    "E3.0 lying face": "🤥",
    "E0.6 relieved face": "😌",
    "E0.6 pensive face": "😔",
    "E0.6 sleepy face": "😪",
    "E3.0 drooling face": "🤤",
    "E1.0 sleeping face": "😴",
    "E0.6 face with medical mask": "😷",
    "E1.0 face with thermometer": "🤒",
    "E1.0 face with head-bandage": "🤕",
    "E3.0 nauseated face": "🤢",
    "E5.0 face vomiting": "🤮",
    "E3.0 sneezing face": "🤧",
    "E11.0 hot face": "🥵",
    "E11.0 cold face": "🥶",
    "E11.0 woozy face": "🥴",
    "E0.6 dizzy face": "😵",
    "E5.0 exploding head": "🤯",
    "E3.0 cowboy hat face": "🤠",
    "E11.0 partying face": "🥳",
    "E13.0 disguised face": "🥸",
    "E1.0 smiling face with sunglasses": "😎",
    "E1.0 nerd face": "🤓",
    "E5.0 face with monocle": "🧐",
    "E1.0 confused face": "😕",
    "E1.0 worried face": "😟",
    "E1.0 slightly frowning face": "🙁",
    "E0.7 frowning face": "☹️",
    "E1.0 face with open mouth": "😮",
    "E1.0 hushed face": "😯",
    "E0.6 astonished face": "😲",
    "E0.6 flushed face": "😳",
    "E11.0 pleading face": "🥺",
    "E1.0 frowning face with open mouth": "😦",
    "E1.0 anguished face": "😧",
    "E0.6 fearful face": "😨",
    "E0.6 anxious face with sweat": "😰",
    "E0.6 sad but relieved face": "😥",
    "E0.6 crying face": "😢",
    "E0.6 loudly crying face": "😭",
    "E0.6 face screaming in fear": "😱",
    "E0.6 confounded face": "😖",
    "E0.6 persevering face": "😣",
    "E0.6 disappointed face": "😞",
    "E0.6 downcast face with sweat": "😓",
    "E0.6 weary face": "😩",
    "E0.6 tired face": "😫",
    "E12.0 yawning face": "🥱",
    "E0.6 face with steam from nose": "😤",
    "E0.6 pouting face": "😡",
    "E0.6 angry face": "😠",
    "E5.0 face with symbols on mouth": "🤬",
    "E1.0 smiling face with horns": "😈",
    "E0.6 angry face with horns": "👿",
    "E0.6 skull": "💀",
    "E1.0 skull and crossbones": "☠️",
    "E0.6 pile of poo": "💩",
    "E3.0 clown face": "🤡",
    "E0.6 ogre": "👹",
    "E0.6 goblin": "👺",
    "E0.6 ghost": "👻",
    "E0.6 alien": "👽",
    "E0.6 alien monster": "👾",
    "E1.0 robot": "🤖",
    "E0.6 grinning cat": "😺",
    "E0.6 grinning cat with smiling eyes": "😸",
    "E0.6 cat with tears of joy": "😹",
    "E0.6 smiling cat with heart-eyes": "😻",
    "E0.6 cat with wry smile": "😼",
    "E0.6 kissing cat": "😽",
    "E0.6 weary cat": "🙀",
    "E0.6 crying cat": "😿",
    "E0.6 pouting cat": "😾",
    "E0.6 see-no-evil monkey": "🙈",
    "E0.6 hear-no-evil monkey": "🙉",
    "E0.6 speak-no-evil monkey": "🙊",
    "E0.6 kiss mark": "💋",
    "E0.6 love letter": "💌",
    "E0.6 heart with arrow": "💘",
    "E0.6 heart with ribbon": "💝",
    "E0.6 sparkling heart": "💖",
    "E0.6 growing heart": "💗",
    "E0.6 beating heart": "💓",
    "E0.6 revolving hearts": "💞",
    "E0.6 two hearts": "💕",
    "E0.6 heart decoration": "💟",
    "E1.0 heart exclamation": "❣️",
    "E0.6 broken heart": "💔",
    "E0.6 red heart": "❤️",
    "E5.0 orange heart": "🧡",
    "E0.6 yellow heart": "💛",
    "E0.6 green heart": "💚",
    "E0.6 blue heart": "💙",
    "E0.6 purple heart": "💜",
    "E12.0 brown heart": "🤎",
    "E3.0 black heart": "🖤",
    "E12.0 white heart": "🤍",
    "E0.6 hundred points": "💯",
    "E0.6 anger symbol": "💢",
    "E0.6 collision": "💥",
    "E0.6 dizzy": "💫",
    "E0.6 sweat droplets": "💦",
    "E0.6 dashing away": "💨",
    "E0.7 hole": "🕳️",
    "E0.6 bomb": "💣",
    "E0.6 speech balloon": "💬",
    "E2.0 eye in speech bubble": "👁️‍🗨️",
    "E2.0 left speech bubble": "🗨️",
    "E0.7 right anger bubble": "🗯️",
    "E1.0 thought balloon": "💭",
    "E0.6 zzz": "💤",
    "E0.6 waving hand": "👋",
    "E3.0 raised back of hand": "🤚",
    "E0.7 hand with fingers splayed": "🖐️",
    "E1.0 hand with fingers splayed: light skin tone": "🖐🏻",
    "E1.0 hand with fingers splayed: medium-light skin tone": "🖐🏼",
    "E1.0 hand with fingers splayed: medium skin tone": "🖐🏽",
    "E1.0 hand with fingers splayed: medium-dark skin tone": "🖐🏾",
    "E1.0 hand with fingers splayed: dark skin tone": "🖐🏿",
    "E0.6 raised hand": "✋",
    "E1.0 vulcan salute": "🖖",
    "E0.6 OK hand": "👌",
    "E13.0 pinched fingers": "🤌",
    "E12.0 pinching hand": "🤏",
    "E0.6 victory hand": "✌️",
    "E1.0 victory hand: light skin tone": "✌🏻",
    "E1.0 victory hand: medium-light skin tone": "✌🏼",
    "E1.0 victory hand: medium skin tone": "✌🏽",
    "E1.0 victory hand: medium-dark skin tone": "✌🏾",
    "E1.0 victory hand: dark skin tone": "✌🏿",
    "E3.0 crossed fingers": "🤞",
    "E5.0 love-you gesture": "🤟",
    "E1.0 sign of the horns": "🤘",
    "E3.0 call me hand": "🤙",
    "E0.6 backhand index pointing left": "👈",
    "E0.6 backhand index pointing right": "👉",
    "E0.6 backhand index pointing up": "👆",
    "E1.0 middle finger": "🖕",
    "E0.6 backhand index pointing down": "👇",
    "E0.6 index pointing up": "☝️",
    "E1.0 index pointing up: light skin tone": "☝🏻",
    "E1.0 index pointing up: medium-light skin tone": "☝🏼",
    "E1.0 index pointing up: medium skin tone": "☝🏽",
    "E1.0 index pointing up: medium-dark skin tone": "☝🏾",
    "E1.0 index pointing up: dark skin tone": "☝🏿",
    "E0.6 thumbs up": "👍",
    "E0.6 thumbs down": "👎",
    "E0.6 raised fist": "✊",
    "E0.6 oncoming fist": "👊",
    "E3.0 left-facing fist": "🤛",
    "E3.0 right-facing fist": "🤜",
    "E0.6 clapping hands": "👏",
    "E0.6 raising hands": "🙌",
    "E0.6 open hands": "👐",
    "E5.0 palms up together": "🤲",
    "E3.0 handshake": "🤝",
    "E0.6 folded hands": "🙏",
    "E0.7 writing hand": "✍️",
    "E1.0 writing hand: light skin tone": "✍🏻",
    "E1.0 writing hand: medium-light skin tone": "✍🏼",
    "E1.0 writing hand: medium skin tone": "✍🏽",
    "E1.0 writing hand: medium-dark skin tone": "✍🏾",
    "E1.0 writing hand: dark skin tone": "✍🏿",
    "E0.6 nail polish": "💅",
    "E3.0 selfie": "🤳",
    "E0.6 flexed biceps": "💪",
    "E12.0 mechanical arm": "🦾",
    "E12.0 mechanical leg": "🦿",
    "E11.0 leg": "🦵",
    "E11.0 foot": "🦶",
    "E0.6 ear": "👂",
    "E12.0 ear with hearing aid": "🦻",
    "E0.6 nose": "👃",
    "E5.0 brain": "🧠",
    "E13.0 anatomical heart": "🫀",
    "E13.0 lungs": "🫁",
    "E11.0 tooth": "🦷",
    "E11.0 bone": "🦴",
    "E0.6 eyes": "👀",
    "E0.7 eye": "👁️",
    "E0.6 tongue": "👅",
    "E0.6 mouth": "👄",
    "E0.6 baby": "👶",
    "E5.0 child": "🧒",
    "E0.6 boy": "👦",
    "E0.6 girl": "👧",
    "E5.0 person": "🧑",
    "E0.6 person: blond hair": "👱",
    "E0.6 man": "👨",
    "E5.0 man: beard": "🧔",
    "E11.0 man: red hair": "👨‍🦰",
    "E0.6 woman": "👩",
    "E12.1 person: red hair": "🧑‍🦰",
    "E11.0 woman: curly hair": "👩‍🦱",
    "E12.1 person: curly hair": "🧑‍🦱",
    "E11.0 woman: white hair": "👩‍🦳",
    "E12.1 person: white hair": "🧑‍🦳",
    "E11.0 woman: bald": "👩‍🦲",
    "E12.1 person: bald": "🧑‍🦲",
    "E4.0 woman: blond hair": "👱‍♀️",
    "E5.0 older person": "🧓",
    "E0.6 old man": "👴",
    "E0.6 old woman": "👵",
    "E0.6 person frowning": "🙍",
    "E0.6 person pouting": "🙎",
    "E0.6 person gesturing NO": "🙅",
    "E0.6 person gesturing OK": "🙆",
    "E0.6 person tipping hand": "💁",
    "E0.6 person raising hand": "🙋",
    "E12.0 deaf person": "🧏",
    "E0.6 person bowing": "🙇",
    "E3.0 person facepalming": "🤦",
    "E3.0 person shrugging": "🤷",
    "E12.1 health worker": "🧑‍⚕️",
    "E4.0 man health worker": "👨‍⚕️",
    "E4.0 woman health worker": "👩‍⚕️",
    "E12.1 student": "🧑‍🎓",
    "E4.0 man student": "👨‍🎓",
    "E4.0 woman student": "👩‍🎓",
    "E12.1 teacher": "🧑‍🏫",
    "E4.0 man teacher": "👨‍🏫",
    "E4.0 woman teacher": "👩‍🏫",
    "E12.1 judge": "🧑‍⚖️",
    "E4.0 man judge": "👨‍⚖️",
    "E4.0 woman judge": "👩‍⚖️",
    "E12.1 farmer": "🧑‍🌾",
    "E4.0 man farmer": "👨‍🌾",
    "E4.0 woman farmer": "👩‍🌾",
    "E12.1 cook": "🧑‍🍳",
    "E4.0 man cook": "👨‍🍳",
    "E4.0 woman cook": "👩‍🍳",
    "E12.1 mechanic": "🧑‍🔧",
    "E4.0 man mechanic": "👨‍🔧",
    "E4.0 woman mechanic": "👩‍🔧",
    "E12.1 factory worker": "🧑‍🏭",
    "E4.0 man factory worker": "👨‍🏭",
    "E4.0 woman factory worker": "👩‍🏭",
    "E12.1 office worker": "🧑‍💼",
    "E4.0 man office worker": "👨‍💼",
    "E4.0 woman office worker": "👩‍💼",
    "E12.1 scientist": "🧑‍🔬",
    "E4.0 man scientist": "👨‍🔬",
    "E4.0 woman scientist": "👩‍🔬",
    "E12.1 technologist": "🧑‍💻",
    "E4.0 man technologist": "👨‍💻",
    "E4.0 woman technologist": "👩‍💻",
    "E12.1 singer": "🧑‍🎤",
    "E4.0 man singer": "👨‍🎤",
    "E4.0 woman singer": "👩‍🎤",
    "E12.1 artist": "🧑‍🎨",
    "E4.0 man artist": "👨‍🎨",
    "E4.0 woman artist": "👩‍🎨",
    "E12.1 pilot": "🧑‍✈️",
    "E4.0 man pilot": "👨‍✈️",
    "E4.0 woman pilot": "👩‍✈️",
    "E12.1 astronaut": "🧑‍🚀",
    "E4.0 man astronaut": "👨‍🚀",
    "E4.0 woman astronaut": "👩‍🚀",
    "E12.1 firefighter": "🧑‍🚒",
    "E4.0 man firefighter": "👨‍🚒",
    "E4.0 woman firefighter": "👩‍🚒",
    "E0.6 police officer": "👮",
    "E0.7 detective": "🕵️",
    "E2.0 detective: light skin tone": "🕵🏻",
    "E2.0 detective: medium-light skin tone": "🕵🏼",
    "E2.0 detective: medium skin tone": "🕵🏽",
    "E2.0 detective: medium-dark skin tone": "🕵🏾",
    "E2.0 detective: dark skin tone": "🕵🏿",
    "E4.0 man detective": "🕵️‍♂️",
    "E4.0 man detective: light skin tone": "🕵🏻‍♂️",
    "E4.0 man detective: medium-light skin tone": "🕵🏼‍♂️",
    "E4.0 man detective: medium skin tone": "🕵🏽‍♂️",
    "E4.0 man detective: medium-dark skin tone": "🕵🏾‍♂️",
    "E4.0 man detective: dark skin tone": "🕵🏿‍♂️",
    "E4.0 woman detective": "🕵️‍♀️",
    "E4.0 woman detective: light skin tone": "🕵🏻‍♀️",
    "E4.0 woman detective: medium-light skin tone": "🕵🏼‍♀️",
    "E4.0 woman detective: medium skin tone": "🕵🏽‍♀️",
    "E4.0 woman detective: medium-dark skin tone": "🕵🏾‍♀️",
    "E4.0 woman detective: dark skin tone": "🕵🏿‍♀️",
    "E0.6 guard": "💂",
    "E13.0 ninja": "🥷",
    "E0.6 construction worker": "👷",
    "E3.0 prince": "🤴",
    "E0.6 princess": "👸",
    "E0.6 person wearing turban": "👳",
    "E0.6 person with skullcap": "👲",
    "E5.0 woman with headscarf": "🧕",
    "E3.0 person in tuxedo": "🤵",
    "E0.6 person with veil": "👰",
    "E3.0 pregnant woman": "🤰",
    "E5.0 breast-feeding": "🤱",
    "E13.0 woman feeding baby": "👩‍🍼",
    "E13.0 man feeding baby": "👨‍🍼",
    "E13.0 person feeding baby": "🧑‍🍼",
    "E0.6 baby angel": "👼",
    "E0.6 Santa Claus": "🎅",
    "E3.0 Mrs. Claus": "🤶",
    "E13.0 mx claus": "🧑‍🎄",
    "E11.0 superhero": "🦸",
    "E11.0 supervillain": "🦹",
    "E5.0 mage": "🧙",
    "E5.0 fairy": "🧚",
    "E5.0 vampire": "🧛",
    "E5.0 merperson": "🧜",
    "E5.0 elf": "🧝",
    "E5.0 genie": "🧞",
    "E5.0 zombie": "🧟",
    "E0.6 person getting massage": "💆",
    "E0.6 person getting haircut": "💇",
    "E0.6 person walking": "🚶",
    "E12.0 person standing": "🧍",
    "E12.0 person kneeling": "🧎",
    "E12.1 person with white cane": "🧑‍🦯",
    "E12.0 man with white cane": "👨‍🦯",
    "E12.0 woman with white cane": "👩‍🦯",
    "E12.1 person in motorized wheelchair": "🧑‍🦼",
    "E12.0 man in motorized wheelchair": "👨‍🦼",
    "E12.0 woman in motorized wheelchair": "👩‍🦼",
    "E12.1 person in manual wheelchair": "🧑‍🦽",
    "E12.0 man in manual wheelchair": "👨‍🦽",
    "E12.0 woman in manual wheelchair": "👩‍🦽",
    "E0.6 person running": "🏃",
    "E0.6 woman dancing": "💃",
    "E3.0 man dancing": "🕺",
    "E0.7 person in suit levitating": "🕴️",
    "E4.0 person in suit levitating: light skin tone": "🕴🏻",
    "E4.0 person in suit levitating: medium-light skin tone": "🕴🏼",
    "E4.0 person in suit levitating: medium skin tone": "🕴🏽",
    "E4.0 person in suit levitating: medium-dark skin tone": "🕴🏾",
    "E4.0 person in suit levitating: dark skin tone": "🕴🏿",
    "E0.6 people with bunny ears": "👯",
    "E5.0 person in steamy room": "🧖",
    "E5.0 person climbing": "🧗",
    "E3.0 person fencing": "🤺",
    "E1.0 horse racing": "🏇",
    "E0.7 skier": "⛷️",
    "E0.6 snowboarder": "🏂",
    "E0.7 person golfing": "🏌️",
    "E4.0 person golfing: light skin tone": "🏌🏻",
    "E4.0 person golfing: medium-light skin tone": "🏌🏼",
    "E4.0 person golfing: medium skin tone": "🏌🏽",
    "E4.0 person golfing: medium-dark skin tone": "🏌🏾",
    "E4.0 person golfing: dark skin tone": "🏌🏿",
    "E4.0 man golfing": "🏌️‍♂️",
    "E4.0 man golfing: light skin tone": "🏌🏻‍♂️",
    "E4.0 man golfing: medium-light skin tone": "🏌🏼‍♂️",
    "E4.0 man golfing: medium skin tone": "🏌🏽‍♂️",
    "E4.0 man golfing: medium-dark skin tone": "🏌🏾‍♂️",
    "E4.0 man golfing: dark skin tone": "🏌🏿‍♂️",
    "E4.0 woman golfing": "🏌️‍♀️",
    "E4.0 woman golfing: light skin tone": "🏌🏻‍♀️",
    "E4.0 woman golfing: medium-light skin tone": "🏌🏼‍♀️",
    "E4.0 woman golfing: medium skin tone": "🏌🏽‍♀️",
    "E4.0 woman golfing: medium-dark skin tone": "🏌🏾‍♀️",
    "E4.0 woman golfing: dark skin tone": "🏌🏿‍♀️",
    "E0.6 person surfing": "🏄",
    "E1.0 person rowing boat": "🚣",
    "E0.6 person swimming": "🏊",
    "E0.7 person bouncing ball": "⛹️",
    "E2.0 person bouncing ball: light skin tone": "⛹🏻",
    "E2.0 person bouncing ball: medium-light skin tone": "⛹🏼",
    "E2.0 person bouncing ball: medium skin tone": "⛹🏽",
    "E2.0 person bouncing ball: medium-dark skin tone": "⛹🏾",
    "E2.0 person bouncing ball: dark skin tone": "⛹🏿",
    "E4.0 man bouncing ball": "⛹️‍♂️",
    "E4.0 man bouncing ball: light skin tone": "⛹🏻‍♂️",
    "E4.0 man bouncing ball: medium-light skin tone": "⛹🏼‍♂️",
    "E4.0 man bouncing ball: medium skin tone": "⛹🏽‍♂️",
    "E4.0 man bouncing ball: medium-dark skin tone": "⛹🏾‍♂️",
    "E4.0 man bouncing ball: dark skin tone": "⛹🏿‍♂️",
    "E4.0 woman bouncing ball": "⛹️‍♀️",
    "E4.0 woman bouncing ball: light skin tone": "⛹🏻‍♀️",
    "E4.0 woman bouncing ball: medium-light skin tone": "⛹🏼‍♀️",
    "E4.0 woman bouncing ball: medium skin tone": "⛹🏽‍♀️",
    "E4.0 woman bouncing ball: medium-dark skin tone": "⛹🏾‍♀️",
    "E4.0 woman bouncing ball: dark skin tone": "⛹🏿‍♀️",
    "E0.7 person lifting weights": "🏋️",
    "E2.0 person lifting weights: light skin tone": "🏋🏻",
    "E2.0 person lifting weights: medium-light skin tone": "🏋🏼",
    "E2.0 person lifting weights: medium skin tone": "🏋🏽",
    "E2.0 person lifting weights: medium-dark skin tone": "🏋🏾",
    "E2.0 person lifting weights: dark skin tone": "🏋🏿",
    "E4.0 man lifting weights": "🏋️‍♂️",
    "E4.0 man lifting weights: light skin tone": "🏋🏻‍♂️",
    "E4.0 man lifting weights: medium-light skin tone": "🏋🏼‍♂️",
    "E4.0 man lifting weights: medium skin tone": "🏋🏽‍♂️",
    "E4.0 man lifting weights: medium-dark skin tone": "🏋🏾‍♂️",
    "E4.0 man lifting weights: dark skin tone": "🏋🏿‍♂️",
    "E4.0 woman lifting weights": "🏋️‍♀️",
    "E4.0 woman lifting weights: light skin tone": "🏋🏻‍♀️",
    "E4.0 woman lifting weights: medium-light skin tone": "🏋🏼‍♀️",
    "E4.0 woman lifting weights: medium skin tone": "🏋🏽‍♀️",
    "E4.0 woman lifting weights: medium-dark skin tone": "🏋🏾‍♀️",
    "E4.0 woman lifting weights: dark skin tone": "🏋🏿‍♀️",
    "E1.0 person biking": "🚴",
    "E1.0 person mountain biking": "🚵",
    "E3.0 person cartwheeling": "🤸",
    "E3.0 people wrestling": "🤼",
    "E3.0 person playing water polo": "🤽",
    "E3.0 person playing handball": "🤾",
    "E3.0 person juggling": "🤹",
    "E5.0 person in lotus position": "🧘",
    "E0.6 person taking bath": "🛀",
    "E1.0 person in bed": "🛌",
    "E12.0 people holding hands": "🧑‍🤝‍🧑",
    "E1.0 women holding hands": "👭",
    "E12.1 women holding hands: light skin tone, medium-light skin tone": "👩🏻‍🤝‍👩🏼",
    "E12.0 women holding hands: medium-light skin tone": "👭🏼",
    "E12.1 women holding hands: medium-light skin tone, medium skin tone": "👩🏼‍🤝‍👩🏽",
    "E12.0 women holding hands: medium skin tone": "👭🏽",
    "E12.1 women holding hands: medium skin tone, medium-dark skin tone": "👩🏽‍🤝‍👩🏾",
    "E12.0 women holding hands: medium-dark skin tone": "👭🏾",
    "E12.1 women holding hands: medium-dark skin tone, dark skin tone": "👩🏾‍🤝‍👩🏿",
    "E12.0 women holding hands: dark skin tone": "👭🏿",
    "E0.6 woman and man holding hands": "👫",
    "E12.0 woman and man holding hands: light skin tone, medium-light skin tone": "👩🏻‍🤝‍👨🏼",
    "E12.0 woman and man holding hands: medium-light skin tone": "👫🏼",
    "E12.0 woman and man holding hands: medium-light skin tone, medium skin tone": "👩🏼‍🤝‍👨🏽",
    "E12.0 woman and man holding hands: medium skin tone": "👫🏽",
    "E12.0 woman and man holding hands: medium skin tone, medium-dark skin tone": "👩🏽‍🤝‍👨🏾",
    "E12.0 woman and man holding hands: medium-dark skin tone": "👫🏾",
    "E12.0 woman and man holding hands: medium-dark skin tone, dark skin tone": "👩🏾‍🤝‍👨🏿",
    "E12.0 woman and man holding hands: dark skin tone": "👫🏿",
    "E1.0 men holding hands": "👬",
    "E12.1 men holding hands: light skin tone, medium-light skin tone": "👨🏻‍🤝‍👨🏼",
    "E12.0 men holding hands: medium-light skin tone": "👬🏼",
    "E12.1 men holding hands: medium-light skin tone, medium skin tone": "👨🏼‍🤝‍👨🏽",
    "E12.0 men holding hands: medium skin tone": "👬🏽",
    "E12.1 men holding hands: medium skin tone, medium-dark skin tone": "👨🏽‍🤝‍👨🏾",
    "E12.0 men holding hands: medium-dark skin tone": "👬🏾",
    "E12.1 men holding hands: medium-dark skin tone, dark skin tone": "👨🏾‍🤝‍👨🏿",
    "E12.0 men holding hands: dark skin tone": "👬🏿",
    "E0.6 kiss": "💏",
    "E2.0 kiss: woman, man": "👩‍❤️‍💋‍👨",
    "E2.0 kiss: man, man": "👨‍❤️‍💋‍👨",
    "E2.0 kiss: woman, woman": "👩‍❤️‍💋‍👩",
    "E0.6 couple with heart": "💑",
    "E2.0 couple with heart: woman, man": "👩‍❤️‍👨",
    "E2.0 couple with heart: man, man": "👨‍❤️‍👨",
    "E2.0 couple with heart: woman, woman": "👩‍❤️‍👩",
    "E0.6 family": "👪",
    "E2.0 family: man, woman, boy": "👨‍👩‍👦",
    "E2.0 family: woman, woman, boy": "👩‍👩‍👦",
    "E4.0 family: man, boy": "👨‍👦",
    "E4.0 family: woman, boy": "👩‍👦",
    "E0.7 speaking head": "🗣️",
    "E0.6 bust in silhouette": "👤",
    "E1.0 busts in silhouette": "👥",
    "E13.0 people hugging": "🫂",
    "E0.6 footprints": "👣",
    "E0.6 monkey face": "🐵",
    "E0.6 monkey": "🐒",
    "E3.0 gorilla": "🦍",
    "E12.0 orangutan": "🦧",
    "E0.6 dog face": "🐶",
    "E0.7 dog": "🐕",
    "E12.0 guide dog": "🦮",
    "E12.0 service dog": "🐕‍🦺",
    "E0.6 poodle": "🐩",
    "E0.6 wolf": "🐺",
    "E3.0 fox": "🦊",
    "E11.0 raccoon": "🦝",
    "E0.6 cat face": "🐱",
    "E0.7 cat": "🐈",
    "E1.0 lion": "🦁",
    "E0.6 tiger face": "🐯",
    "E1.0 tiger": "🐅",
    "E1.0 leopard": "🐆",
    "E0.6 horse face": "🐴",
    "E0.6 horse": "🐎",
    "E1.0 unicorn": "🦄",
    "E5.0 zebra": "🦓",
    "E3.0 deer": "🦌",
    "E13.0 bison": "🦬",
    "E0.6 cow face": "🐮",
    "E1.0 ox": "🐂",
    "E1.0 water buffalo": "🐃",
    "E1.0 cow": "🐄",
    "E0.6 pig face": "🐷",
    "E1.0 pig": "🐖",
    "E0.6 boar": "🐗",
    "E0.6 pig nose": "🐽",
    "E1.0 ram": "🐏",
    "E0.6 ewe": "🐑",
    "E1.0 goat": "🐐",
    "E1.0 camel": "🐪",
    "E0.6 two-hump camel": "🐫",
    "E11.0 llama": "🦙",
    "E5.0 giraffe": "🦒",
    "E0.6 elephant": "🐘",
    "E13.0 mammoth": "🦣",
    "E3.0 rhinoceros": "🦏",
    "E11.0 hippopotamus": "🦛",
    "E0.6 mouse face": "🐭",
    "E1.0 mouse": "🐁",
    "E1.0 rat": "🐀",
    "E0.6 hamster": "🐹",
    "E0.6 rabbit face": "🐰",
    "E1.0 rabbit": "🐇",
    "E0.7 chipmunk": "🐿️",
    "E13.0 beaver": "🦫",
    "E5.0 hedgehog": "🦔",
    "E3.0 bat": "🦇",
    "E0.6 bear": "🐻",
    "E0.6 koala": "🐨",
    "E0.6 panda": "🐼",
    "E12.0 sloth": "🦥",
    "E12.0 otter": "🦦",
    "E12.0 skunk": "🦨",
    "E11.0 kangaroo": "🦘",
    "E11.0 badger": "🦡",
    "E0.6 paw prints": "🐾",
    "E1.0 turkey": "🦃",
    "E0.6 chicken": "🐔",
    "E1.0 rooster": "🐓",
    "E0.6 hatching chick": "🐣",
    "E0.6 baby chick": "🐤",
    "E0.6 front-facing baby chick": "🐥",
    "E0.6 bird": "🐦",
    "E0.6 penguin": "🐧",
    "E0.7 dove": "🕊️",
    "E3.0 eagle": "🦅",
    "E3.0 duck": "🦆",
    "E11.0 swan": "🦢",
    "E3.0 owl": "🦉",
    "E13.0 dodo": "🦤",
    "E13.0 feather": "🪶",
    "E12.0 flamingo": "🦩",
    "E11.0 peacock": "🦚",
    "E11.0 parrot": "🦜",
    "E0.6 frog": "🐸",
    "E1.0 crocodile": "🐊",
    "E0.6 turtle": "🐢",
    "E3.0 lizard": "🦎",
    "E0.6 snake": "🐍",
    "E0.6 dragon face": "🐲",
    "E1.0 dragon": "🐉",
    "E5.0 sauropod": "🦕",
    "E5.0 T-Rex": "🦖",
    "E0.6 spouting whale": "🐳",
    "E1.0 whale": "🐋",
    "E0.6 dolphin": "🐬",
    "E13.0 seal": "🦭",
    "E0.6 fish": "🐟",
    "E0.6 tropical fish": "🐠",
    "E0.6 blowfish": "🐡",
    "E3.0 shark": "🦈",
    "E0.6 octopus": "🐙",
    "E0.6 spiral shell": "🐚",
    "E0.6 snail": "🐌",
    "E3.0 butterfly": "🦋",
    "E0.6 bug": "🐛",
    "E0.6 ant": "🐜",
    "E0.6 honeybee": "🐝",
    "E13.0 beetle": "🪲",
    "E0.6 lady beetle": "🐞",
    "E5.0 cricket": "🦗",
    "E13.0 cockroach": "🪳",
    "E0.7 spider": "🕷️",
    "E0.7 spider web": "🕸️",
    "E1.0 scorpion": "🦂",
    "E11.0 mosquito": "🦟",
    "E13.0 fly": "🪰",
    "E13.0 worm": "🪱",
    "E11.0 microbe": "🦠",
    "E0.6 bouquet": "💐",
    "E0.6 cherry blossom": "🌸",
    "E0.6 white flower": "💮",
    "E0.7 rosette": "🏵️",
    "E0.6 rose": "🌹",
    "E3.0 wilted flower": "🥀",
    "E0.6 hibiscus": "🌺",
    "E0.6 sunflower": "🌻",
    "E0.6 blossom": "🌼",
    "E0.6 tulip": "🌷",
    "E0.6 seedling": "🌱",
    "E13.0 potted plant": "🪴",
    "E1.0 evergreen tree": "🌲",
    "E1.0 deciduous tree": "🌳",
    "E0.6 palm tree": "🌴",
    "E0.6 cactus": "🌵",
    "E0.6 sheaf of rice": "🌾",
    "E0.6 herb": "🌿",
    "E1.0 shamrock": "☘️",
    "E0.6 four leaf clover": "🍀",
    "E0.6 maple leaf": "🍁",
    "E0.6 fallen leaf": "🍂",
    "E0.6 leaf fluttering in wind": "🍃",
    "E0.6 grapes": "🍇",
    "E0.6 melon": "🍈",
    "E0.6 watermelon": "🍉",
    "E0.6 tangerine": "🍊",
    "E1.0 lemon": "🍋",
    "E0.6 banana": "🍌",
    "E0.6 pineapple": "🍍",
    "E11.0 mango": "🥭",
    "E0.6 red apple": "🍎",
    "E0.6 green apple": "🍏",
    "E1.0 pear": "🍐",
    "E0.6 peach": "🍑",
    "E0.6 cherries": "🍒",
    "E0.6 strawberry": "🍓",
    "E13.0 blueberries": "🫐",
    "E3.0 kiwi fruit": "🥝",
    "E0.6 tomato": "🍅",
    "E13.0 olive": "🫒",
    "E5.0 coconut": "🥥",
    "E3.0 avocado": "🥑",
    "E0.6 eggplant": "🍆",
    "E3.0 potato": "🥔",
    "E3.0 carrot": "🥕",
    "E0.6 ear of corn": "🌽",
    "E0.7 hot pepper": "🌶️",
    "E13.0 bell pepper": "🫑",
    "E3.0 cucumber": "🥒",
    "E11.0 leafy green": "🥬",
    "E5.0 broccoli": "🥦",
    "E12.0 garlic": "🧄",
    "E12.0 onion": "🧅",
    "E0.6 mushroom": "🍄",
    "E3.0 peanuts": "🥜",
    "E0.6 chestnut": "🌰",
    "E0.6 bread": "🍞",
    "E3.0 croissant": "🥐",
    "E3.0 baguette bread": "🥖",
    "E13.0 flatbread": "🫓",
    "E5.0 pretzel": "🥨",
    "E11.0 bagel": "🥯",
    "E3.0 pancakes": "🥞",
    "E12.0 waffle": "🧇",
    "E1.0 cheese wedge": "🧀",
    "E0.6 meat on bone": "🍖",
    "E0.6 poultry leg": "🍗",
    "E5.0 cut of meat": "🥩",
    "E3.0 bacon": "🥓",
    "E0.6 hamburger": "🍔",
    "E0.6 french fries": "🍟",
    "E0.6 pizza": "🍕",
    "E1.0 hot dog": "🌭",
    "E5.0 sandwich": "🥪",
    "E1.0 taco": "🌮",
    "E1.0 burrito": "🌯",
    "E13.0 tamale": "🫔",
    "E3.0 stuffed flatbread": "🥙",
    "E12.0 falafel": "🧆",
    "E3.0 egg": "🥚",
    "E0.6 cooking": "🍳",
    "E3.0 shallow pan of food": "🥘",
    "E0.6 pot of food": "🍲",
    "E13.0 fondue": "🫕",
    "E5.0 bowl with spoon": "🥣",
    "E3.0 green salad": "🥗",
    "E1.0 popcorn": "🍿",
    "E12.0 butter": "🧈",
    "E11.0 salt": "🧂",
    "E5.0 canned food": "🥫",
    "E0.6 bento box": "🍱",
    "E0.6 rice cracker": "🍘",
    "E0.6 rice ball": "🍙",
    "E0.6 cooked rice": "🍚",
    "E0.6 curry rice": "🍛",
    "E0.6 steaming bowl": "🍜",
    "E0.6 spaghetti": "🍝",
    "E0.6 roasted sweet potato": "🍠",
    "E0.6 oden": "🍢",
    "E0.6 sushi": "🍣",
    "E0.6 fried shrimp": "🍤",
    "E0.6 fish cake with swirl": "🍥",
    "E11.0 moon cake": "🥮",
    "E0.6 dango": "🍡",
    "E5.0 dumpling": "🥟",
    "E5.0 fortune cookie": "🥠",
    "E5.0 takeout box": "🥡",
    "E1.0 crab": "🦀",
    "E11.0 lobster": "🦞",
    "E3.0 shrimp": "🦐",
    "E3.0 squid": "🦑",
    "E12.0 oyster": "🦪",
    "E0.6 soft ice cream": "🍦",
    "E0.6 shaved ice": "🍧",
    "E0.6 ice cream": "🍨",
    "E0.6 doughnut": "🍩",
    "E0.6 cookie": "🍪",
    "E0.6 birthday cake": "🎂",
    "E0.6 shortcake": "🍰",
    "E11.0 cupcake": "🧁",
    "E5.0 pie": "🥧",
    "E0.6 chocolate bar": "🍫",
    "E0.6 candy": "🍬",
    "E0.6 lollipop": "🍭",
    "E0.6 custard": "🍮",
    "E0.6 honey pot": "🍯",
    "E1.0 baby bottle": "🍼",
    "E3.0 glass of milk": "🥛",
    "E0.6 hot beverage": "☕",
    "E13.0 teapot": "🫖",
    "E0.6 teacup without handle": "🍵",
    "E0.6 sake": "🍶",
    "E1.0 bottle with popping cork": "🍾",
    "E0.6 wine glass": "🍷",
    "E0.6 cocktail glass": "🍸",
    "E0.6 tropical drink": "🍹",
    "E0.6 beer mug": "🍺",
    "E0.6 clinking beer mugs": "🍻",
    "E3.0 clinking glasses": "🥂",
    "E3.0 tumbler glass": "🥃",
    "E5.0 cup with straw": "🥤",
    "E13.0 bubble tea": "🧋",
    "E12.0 beverage box": "🧃",
    "E12.0 mate": "🧉",
    "E12.0 ice": "🧊",
    "E5.0 chopsticks": "🥢",
    "E0.7 fork and knife with plate": "🍽️",
    "E0.6 fork and knife": "🍴",
    "E3.0 spoon": "🥄",
    "E0.6 kitchen knife": "🔪",
    "E1.0 amphora": "🏺",
    "E0.7 globe showing Europe-Africa": "🌍",
    "E0.7 globe showing Americas": "🌎",
    "E0.6 globe showing Asia-Australia": "🌏",
    "E1.0 globe with meridians": "🌐",
    "E0.7 world map": "🗺️",
    "E0.6 map of Japan": "🗾",
    "E11.0 compass": "🧭",
    "E0.7 snow-capped mountain": "🏔️",
    "E0.7 mountain": "⛰️",
    "E0.6 volcano": "🌋",
    "E0.6 mount fuji": "🗻",
    "E0.7 camping": "🏕️",
    "E0.7 beach with umbrella": "🏖️",
    "E0.7 desert": "🏜️",
    "E0.7 desert island": "🏝️",
    "E0.7 national park": "🏞️",
    "E0.7 stadium": "🏟️",
    "E0.7 classical building": "🏛️",
    "E0.7 building construction": "🏗️",
    "E11.0 brick": "🧱",
    "E13.0 rock": "🪨",
    "E13.0 wood": "🪵",
    "E13.0 hut": "🛖",
    "E0.7 houses": "🏘️",
    "E0.7 derelict house": "🏚️",
    "E0.6 house": "🏠",
    "E0.6 house with garden": "🏡",
    "E0.6 office building": "🏢",
    "E0.6 Japanese post office": "🏣",
    "E1.0 post office": "🏤",
    "E0.6 hospital": "🏥",
    "E0.6 bank": "🏦",
    "E0.6 hotel": "🏨",
    "E0.6 love hotel": "🏩",
    "E0.6 convenience store": "🏪",
    "E0.6 school": "🏫",
    "E0.6 department store": "🏬",
    "E0.6 factory": "🏭",
    "E0.6 Japanese castle": "🏯",
    "E0.6 castle": "🏰",
    "E0.6 wedding": "💒",
    "E0.6 Tokyo tower": "🗼",
    "E0.6 Statue of Liberty": "🗽",
    "E0.6 church": "⛪",
    "E1.0 mosque": "🕌",
    "E12.0 hindu temple": "🛕",
    "E1.0 synagogue": "🕍",
    "E0.7 shinto shrine": "⛩️",
    "E1.0 kaaba": "🕋",
    "E0.6 fountain": "⛲",
    "E0.6 tent": "⛺",
    "E0.6 foggy": "🌁",
    "E0.6 night with stars": "🌃",
    "E0.7 cityscape": "🏙️",
    "E0.6 sunrise over mountains": "🌄",
    "E0.6 sunrise": "🌅",
    "E0.6 cityscape at dusk": "🌆",
    "E0.6 sunset": "🌇",
    "E0.6 bridge at night": "🌉",
    "E0.6 hot springs": "♨️",
    "E0.6 carousel horse": "🎠",
    "E0.6 ferris wheel": "🎡",
    "E0.6 roller coaster": "🎢",
    "E0.6 barber pole": "💈",
    "E0.6 circus tent": "🎪",
    "E1.0 locomotive": "🚂",
    "E0.6 railway car": "🚃",
    "E0.6 high-speed train": "🚄",
    "E0.6 bullet train": "🚅",
    "E1.0 train": "🚆",
    "E0.6 metro": "🚇",
    "E1.0 light rail": "🚈",
    "E0.6 station": "🚉",
    "E1.0 tram": "🚊",
    "E1.0 monorail": "🚝",
    "E1.0 mountain railway": "🚞",
    "E1.0 tram car": "🚋",
    "E0.6 bus": "🚌",
    "E0.7 oncoming bus": "🚍",
    "E1.0 trolleybus": "🚎",
    "E1.0 minibus": "🚐",
    "E0.6 ambulance": "🚑",
    "E0.6 fire engine": "🚒",
    "E0.6 police car": "🚓",
    "E0.7 oncoming police car": "🚔",
    "E0.6 taxi": "🚕",
    "E1.0 oncoming taxi": "🚖",
    "E0.6 automobile": "🚗",
    "E0.7 oncoming automobile": "🚘",
    "E0.6 sport utility vehicle": "🚙",
    "E13.0 pickup truck": "🛻",
    "E0.6 delivery truck": "🚚",
    "E1.0 articulated lorry": "🚛",
    "E1.0 tractor": "🚜",
    "E0.7 racing car": "🏎️",
    "E0.7 motorcycle": "🏍️",
    "E3.0 motor scooter": "🛵",
    "E12.0 manual wheelchair": "🦽",
    "E12.0 motorized wheelchair": "🦼",
    "E12.0 auto rickshaw": "🛺",
    "E0.6 bicycle": "🚲",
    "E3.0 kick scooter": "🛴",
    "E11.0 skateboard": "🛹",
    "E13.0 roller skate": "🛼",
    "E0.6 bus stop": "🚏",
    "E0.7 motorway": "🛣️",
    "E0.7 railway track": "🛤️",
    "E0.7 oil drum": "🛢️",
    "E0.6 fuel pump": "⛽",
    "E0.6 police car light": "🚨",
    "E0.6 horizontal traffic light": "🚥",
    "E1.0 vertical traffic light": "🚦",
    "E3.0 stop sign": "🛑",
    "E0.6 construction": "🚧",
    "E0.6 anchor": "⚓",
    "E0.6 sailboat": "⛵",
    "E3.0 canoe": "🛶",
    "E0.6 speedboat": "🚤",
    "E0.7 passenger ship": "🛳️",
    "E0.7 ferry": "⛴️",
    "E0.7 motor boat": "🛥️",
    "E0.6 ship": "🚢",
    "E0.6 airplane": "✈️",
    "E0.7 small airplane": "🛩️",
    "E1.0 airplane departure": "🛫",
    "E1.0 airplane arrival": "🛬",
    "E12.0 parachute": "🪂",
    "E0.6 seat": "💺",
    "E1.0 helicopter": "🚁",
    "E1.0 suspension railway": "🚟",
    "E1.0 mountain cableway": "🚠",
    "E1.0 aerial tramway": "🚡",
    "E0.7 satellite": "🛰️",
    "E0.6 rocket": "🚀",
    "E5.0 flying saucer": "🛸",
    "E0.7 bellhop bell": "🛎️",
    "E11.0 luggage": "🧳",
    "E0.6 hourglass done": "⌛",
    "E0.6 hourglass not done": "⏳",
    "E0.6 watch": "⌚",
    "E0.6 alarm clock": "⏰",
    "E1.0 stopwatch": "⏱️",
    "E1.0 timer clock": "⏲️"
};