name: Build Docs

on:
    push:
        branches: [main, \@next]
    pull_request:
        branches: [main, \@next]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [17.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Build deno
              run: |
                  npm i -g yarn
                  yarn install
                  yarn build:deno
            - name: setup git config
              run: |
                  git config user.name "GitHub Actions Bot"
                  git config user.email "<>"
            - name: commit
              run: |
                  git add .
                  git commit -m "gen docs"
                  git push
