name: Gen Docs

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x, 14.x, 16.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Build docs
              run: |
                  npm i -g yarn
                  yarn install
                  yarn docs
            - name: setup git config
              run: |
                  git config user.name "GitHub Actions Bot"
                  git config user.email "<>"
            - name: commit
              run: |
                  git commit -m "gen docs"
                  git push origin next
